package io.github.larkbatis.processor.emit;

import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.CodeBlock;
import com.palantir.javapoet.FieldSpec;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.ParameterizedTypeName;
import com.palantir.javapoet.TypeName;
import com.palantir.javapoet.TypeSpec;
import io.github.larkbatis.processor.ir.DynamicModel;
import io.github.larkbatis.processor.ir.KeyModel;
import io.github.larkbatis.processor.ir.ColumnNaming;
import io.github.larkbatis.processor.ir.MapperModel;
import io.github.larkbatis.processor.ir.NestedResult;
import io.github.larkbatis.processor.ir.ParamModel;
import io.github.larkbatis.processor.ir.PropertyModel;
import io.github.larkbatis.processor.ir.ReaderAccess;
import io.github.larkbatis.processor.ir.ResultModel;
import io.github.larkbatis.processor.ir.ReturnShape;
import io.github.larkbatis.processor.ir.SqlPiece;
import io.github.larkbatis.processor.ir.StatementKind;
import io.github.larkbatis.processor.ir.StatementModel;
import io.github.larkbatis.processor.ir.ValueKind;
import java.util.ArrayList;
import java.util.IdentityHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.StringJoiner;
import javax.lang.model.element.Modifier;

/**
 * Emits {@code <Mapper>$$Impl}. The hand-written
 * landmark this must reproduce lives at
 * {@code larkbatis-runtime/src/test/java/.../handwritten/UserMapper$$Impl.java}.
 *
 * <p>Shape rules: SQL as a private static constant ({@code ?} already in
 * place); the Connection borrowed via {@code s.conn()} and returned via
 * {@code s.release(c)} in a finally — never try-with-resources;
 * explicit key column names to {@code prepareStatement}; every
 * SQLException through {@code s.translate(e, sql)}.
 */
public final class MapperImplEmitter {

    private MapperImplEmitter() {
    }

    public static String emit(MapperModel mapper, Map<String, ResultModel> resultModels,
            ColumnNaming naming) {
        ClassName mapperInterface = ClassName.get(mapper.packageName(), mapper.simpleName());
        TypeSpec.Builder type = TypeSpec.classBuilder(mapper.implSimpleName())
                .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
                .addSuperinterface(mapperInterface)
                .addAnnotation(EmitSupport.generatedAnnotation())
                .addJavadoc("Generated by LarkBatis from {@link $T} — do not edit.\n"
                        + "Plain JDBC, resolved at build time; the only runtime"
                        + " inputs are parameter values.\n", mapperInterface);
        HandlerFields handlers = new HandlerFields();

        for (StatementModel statement : mapper.statements()) {
            addConstants(type, statement);
            if (statement.resultFqn() != null) {
                addColumnResolver(type, statement.readerAccess(), "cols_" + statement.methodName(),
                        resultModels.get(statement.resultFqn()), naming);
            }
            if (statement.nested() != null) {
                addColumnResolver(type, statement.nested().childAccess(),
                        "ncols_" + statement.methodName(),
                        resultModels.get(statement.nested().childFqn()), naming);
            }
        }

        type.addField(EmitSupport.LIGHT_BATIS_SESSION, "s", Modifier.PRIVATE, Modifier.FINAL);
        type.addMethod(MethodSpec.constructorBuilder()
                .addModifiers(Modifier.PUBLIC)
                .addParameter(EmitSupport.LIGHT_BATIS_SESSION, "s")
                .addStatement("this.s = s")
                .build());

        for (StatementModel statement : mapper.statements()) {
            type.addMethod(method(statement, resultModels, handlers));
        }
        handlers.addTo(type);

        return JavaFile.builder(mapper.packageName(), type.build())
                .skipJavaLangImports(true)
                .indent("    ")
                .build()
                .toString();
    }

    // --- constants -------------------------------------------------------------

    private static void addConstants(TypeSpec.Builder type, StatementModel st) {
        if (st.tracksVariants()) {
            type.addField(FieldSpec.builder(String.class, "STMT_" + st.methodName(),
                            Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
                    .initializer("$S", st.statementId())
                    .build());
        } else if (st.dynamic() == null) {
            type.addField(FieldSpec.builder(String.class, "SQL_" + st.methodName(),
                            Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
                    .initializer("$S", staticSql(st))
                    .build());
        }
        if (st.keys() != null && !st.keys().columns().isEmpty()) {
            CodeBlock.Builder names = CodeBlock.builder();
            for (int i = 0; i < st.keys().columns().size(); i++) {
                names.add(i == 0 ? "$S" : ", $S", st.keys().columns().get(i));
            }
            type.addField(FieldSpec.builder(String[].class, "KEYS_" + st.methodName(),
                            Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
                    .initializer("{ $L }", names.build())
                    .build());
        }
        addColumnConstant(type, st.readerAccess(), "COLS_" + st.methodName());
        if (st.nested() != null) {
            addColumnConstant(type, st.nested().childAccess(), "NCOLS_" + st.methodName());
        }
    }

    private static void addColumnConstant(TypeSpec.Builder type, ReaderAccess access, String name) {
        if (access == null || access.mode() != ReaderAccess.Mode.POSITIONAL_CUSTOM) {
            return;
        }
        StringJoiner positions = new StringJoiner(", ");
        access.columnOrder().forEach(p -> positions.add(String.valueOf(p)));
        type.addField(FieldSpec.builder(int[].class, name,
                        Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
                .initializer("{ $L }", positions.toString())
                .build());
    }

    /**
     * The name-based resolver for a {@code <resultMap>} statement. The generic
     * {@code columns(rs)} on the row reader matches labels against property
     * names; a result map named the columns itself, and those names belong to
     * this one statement — so the switch lives here rather than on the reader.
     */
    private static void addColumnResolver(TypeSpec.Builder type, ReaderAccess access,
            String name, ResultModel result, ColumnNaming naming) {
        if (access == null || access.mode() != ReaderAccess.Mode.NAME_BASED_MAPPED) {
            return;
        }
        MethodSpec.Builder resolver = MethodSpec.methodBuilder(name)
                .addModifiers(Modifier.PRIVATE, Modifier.STATIC)
                .returns(int[].class)
                .addParameter(EmitSupport.RESULT_SET, "rs")
                .addException(EmitSupport.SQL_EXCEPTION)
                .addJavadoc("Column positions for the columns this statement's <resultMap>"
                        + " named,\nresolved from ResultSetMetaData once, on the first row"
                        + ".\n")
                .addStatement("$T md = rs.getMetaData()", EmitSupport.RESULT_SET_META_DATA)
                .addStatement("int[] c = new int[$L]", result.properties().size())
                .beginControlFlow("for (int i = 1, n = md.getColumnCount(); i <= n; i++)")
                .beginControlFlow("switch ($L)", EmitSupport.columnLabelKey(naming, "i"));
        for (int k = 0; k < access.columnNames().size(); k++) {
            String column = access.columnNames().get(k);
            if (column != null) {
                resolver.addCode("case $S:\n$>c[$L] = i;\nbreak;\n$<",
                        naming.keyOf(column), k);
            }
        }
        resolver.addCode("default:\n$>break;\n$<")
                .endControlFlow()
                .endControlFlow()
                .addStatement("return c");
        type.addMethod(resolver.build());
    }

    /** Static SQL: literal text with {@code ?} where {@code #{}} used to be. */
    private static String staticSql(StatementModel st) {
        StringBuilder sql = new StringBuilder();
        for (SqlPiece piece : st.pieces()) {
            if (piece instanceof SqlPiece.Text t) {
                sql.append(t.sql());
            } else if (piece instanceof SqlPiece.Bind) {
                sql.append('?');
            }
        }
        return sql.toString();
    }

    // --- one method --------------------------------------------------------------

    private static MethodSpec method(StatementModel st, Map<String, ResultModel> resultModels,
            HandlerFields handlers) {
        MethodSpec.Builder m = MethodSpec.methodBuilder(st.methodName())
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .returns(returnTypeName(st, resultModels));
        for (ParamModel param : st.params()) {
            m.addParameter(EmitSupport.typeName(param.typeFqn()), param.name());
        }

        // @OrderBy switches: reject-or-accept once, reuse for SQL text
        for (SqlPiece piece : st.pieces()) {
            if (piece instanceof SqlPiece.Dollar d
                    && d.dollarKind() == SqlPiece.Dollar.DollarKind.ORDER_BY) {
                String local = d.accessor() + "Sql";
                m.addStatement("$T $L", String.class, local);
                m.beginControlFlow("switch ($L)", d.accessor());
                for (String allowed : d.allowed()) {
                    m.addCode("case $S:\n$>$L = $S;\nbreak;\n$<", allowed, local, allowed);
                }
                CodeBlock.Builder allowedArray = CodeBlock.builder();
                for (int i = 0; i < d.allowed().size(); i++) {
                    allowedArray.add(i == 0 ? "$S" : ", $S", d.allowed().get(i));
                }
                m.addCode("default:\n$>throw new $T($L, new String[] { $L });\n$<",
                        EmitSupport.REJECTED_EXCEPTION, d.accessor(), allowedArray.build());
                m.endControlFlow();
            }
        }

        String sqlRef;
        if (st.dynamic() != null) {
            sqlRef = "sql";
            assembleDynamicSql(m, st);
            if (st.tracksVariants()) {
                m.addStatement("$T.trackVariants($L, sql)",
                        EmitSupport.LIGHT_BATIS_SQL, "STMT_" + st.methodName());
            }
        } else if (st.hasDollar()) {
            sqlRef = "sql";
            m.addStatement("String sql = $L", spliceExpression(st));
            m.addStatement("$T.trackVariants($L, sql)",
                    EmitSupport.LIGHT_BATIS_SQL, "STMT_" + st.methodName());
        } else {
            sqlRef = "SQL_" + st.methodName();
        }

        if (st.batch() != null) {
            m.beginControlFlow("if ($L.isEmpty())", st.batch().paramName());
            emptyBatchReturn(m, st.returnTypeFqn());
            m.endControlFlow();
        }

        if (st.returnShape() == ReturnShape.STREAM) {
            streamBody(m, st, resultModels, sqlRef, handlers);
            return m.build();
        }

        m.addStatement("$T c = s.conn()", EmitSupport.CONNECTION);
        if (st.keys() != null) {
            if (st.keys().columns().isEmpty()) {
                // build already warned: Oracle ROWID / PostgreSQL all-columns
                m.beginControlFlow("try ($T ps = c.prepareStatement($L, $T.RETURN_GENERATED_KEYS))",
                        EmitSupport.PREPARED_STATEMENT, sqlRef, EmitSupport.SQL_STATEMENT);
            } else {
                m.beginControlFlow("try ($T ps = c.prepareStatement($L, $L))",
                        EmitSupport.PREPARED_STATEMENT, sqlRef, "KEYS_" + st.methodName());
            }
        } else {
            m.beginControlFlow("try ($T ps = c.prepareStatement($L))",
                    EmitSupport.PREPARED_STATEMENT, sqlRef);
        }

        if (st.batch() != null) {
            m.beginControlFlow("for ($T $L : $L)",
                    EmitSupport.typeName(st.batch().elementTypeFqn()),
                    st.batch().loopVar(), st.batch().paramName());
            addBinds(m, st, handlers);
            m.addStatement("ps.addBatch()");
            m.endControlFlow();
            executeBatch(m, st);
        } else {
            addBinds(m, st, handlers);
            if (st.kind() == StatementKind.SELECT) {
                executeQuery(m, st, resultModels, sqlRef);
            } else {
                executeUpdate(m, st, sqlRef);
            }
        }

        m.nextControlFlow("catch ($T e)", EmitSupport.SQL_EXCEPTION);
        m.addStatement("throw s.translate(e, $L)", sqlRef);
        m.nextControlFlow("finally");
        m.addStatement("s.release(c)");
        m.endControlFlow();
        return m.build();
    }

    /** The runtime SQL expression when {@code ${}} splices are present. */
    private static CodeBlock spliceExpression(StatementModel st) {
        CodeBlock.Builder expr = CodeBlock.builder();
        StringBuilder literal = new StringBuilder();
        boolean first = true;
        for (SqlPiece piece : st.pieces()) {
            if (piece instanceof SqlPiece.Text t) {
                literal.append(t.sql());
                continue;
            }
            if (piece instanceof SqlPiece.Bind) {
                literal.append('?');
                continue;
            }
            SqlPiece.Dollar d = (SqlPiece.Dollar) piece;
            if (literal.length() > 0 || first) {
                // a leading literal also guarantees string-typed concatenation
                expr.add(first ? "$S" : " + $S", literal.toString());
                literal.setLength(0);
                first = false;
            }
            expr.add(" + $L", switch (d.dollarKind()) {
                case FRAGMENT -> d.accessor() + ".text()";
                case ENUM_NAME -> d.accessor() + ".name()";
                case CLOSED_VALUE -> d.accessor();
                case ORDER_BY -> d.accessor() + "Sql";
            });
        }
        if (literal.length() > 0 || first) {
            expr.add(first ? "$S" : " + $S", literal.toString());
        }
        return expr.build();
    }

    /**
     * The dynamic body's SQL assembly: condition locals first —
     * computed once, reused for SQL and binding — then one append chain per
     * segment, guarded by the segment's condition.
     */
    private static void assembleDynamicSql(MethodSpec.Builder m, StatementModel st) {
        DynamicModel dyn = st.dynamic();
        for (DynamicModel.CondLocal local : dyn.locals()) {
            m.addStatement("boolean $L = $L", local.name(), local.javaExpr());
        }
        Map<SqlPiece.Foreach, Integer> loopIds = numberForeachLoops(dyn);
        Set<SqlPiece.Foreach> shared = sharedCollections(dyn);
        Set<SqlPiece.Foreach> hoisted = hoistLoopLocals(m, st, dyn, loopIds, shared);
        m.addStatement("$1T sb = new $1T($2L)", StringBuilder.class, capacityOf(dyn));
        for (DynamicModel.Segment segment : dyn.segments()) {
            if (segment.guard() != null) {
                m.beginControlFlow("if ($L)", segment.guard());
            }
            appendPieces(m, st, segment.pieces(), loopIds, hoisted, shared);
            if (segment.guard() != null) {
                m.endControlFlow();
            }
        }
        // A statement opening with a loop that has no `open` starts with the
        // body's joiner space, and the body is emitted once per element — so
        // the space is trimmed off the result, exactly as
        // DynamicContext.getSql() does, rather than out of the body.
        m.addStatement(opensWithBareForeach(dyn)
                ? "String sql = sb.toString().trim()"
                : "String sql = sb.toString()");
    }

    private static boolean opensWithBareForeach(DynamicModel dyn) {
        List<SqlPiece> first = dyn.segments().get(0).pieces();
        return !first.isEmpty() && first.get(0) instanceof SqlPiece.Foreach foreach
                && foreach.open() == null;
    }

    /**
     * Stable numbering of the {@code <foreach>} loops in source order, shared
     * by the SQL pass and the bind pass so the two agree on local names.
     */
    private static Map<SqlPiece.Foreach, Integer> numberForeachLoops(DynamicModel dyn) {
        Map<SqlPiece.Foreach, Integer> ids = new IdentityHashMap<>();
        for (DynamicModel.Segment segment : dyn.segments()) {
            numberForeachLoops(segment.pieces(), ids);
        }
        return ids;
    }

    private static void numberForeachLoops(List<SqlPiece> pieces,
            Map<SqlPiece.Foreach, Integer> ids) {
        for (SqlPiece piece : pieces) {
            if (piece instanceof SqlPiece.Foreach foreach) {
                ids.put(foreach, ids.size());
                numberForeachLoops(foreach.body(), ids);
            }
        }
    }

    /**
     * The {@code <foreach>} loops whose collection is read into a local both
     * passes share: the top-level ones whose accessor is not already a local.
     * A nested loop is left out — its collection hangs off the enclosing loop
     * variable, which has no meaning at method scope.
     *
     * <p>Recomputed rather than threaded, and deterministic from the model, so
     * the SQL pass and the bind pass reach the same answer without having to
     * hand it to each other.
     */
    private static Set<SqlPiece.Foreach> sharedCollections(DynamicModel dyn) {
        Set<SqlPiece.Foreach> shared =
                java.util.Collections.newSetFromMap(new IdentityHashMap<>());
        for (DynamicModel.Segment segment : dyn.segments()) {
            for (SqlPiece piece : segment.pieces()) {
                if (piece instanceof SqlPiece.Foreach foreach && !foreach.accessorIsLocal()) {
                    shared.add(foreach);
                }
            }
        }
        return shared;
    }

    /**
     * Declares, at method scope, the locals a {@code <foreach>} needs the two
     * passes to agree on: the collection itself where it is reached through a
     * getter, and — for a padded loop — the element count and the padded
     * count. Everything else a loop needs is local to its own pass.
     *
     * <p>A loop in an unguarded segment gets its values here; a guarded one
     * gets a declaration here and its assignment inside the guard, where the
     * SQL pass reaches it. The returned set is the first kind.
     */
    private static Set<SqlPiece.Foreach> hoistLoopLocals(MethodSpec.Builder m,
            StatementModel st, DynamicModel dyn, Map<SqlPiece.Foreach, Integer> loopIds,
            Set<SqlPiece.Foreach> shared) {
        Set<SqlPiece.Foreach> initialized =
                java.util.Collections.newSetFromMap(new IdentityHashMap<>());
        for (DynamicModel.Segment segment : dyn.segments()) {
            for (SqlPiece piece : segment.pieces()) {
                if (!(piece instanceof SqlPiece.Foreach foreach)) {
                    continue;
                }
                boolean sharesCollection = shared.contains(foreach);
                if (!sharesCollection && !foreach.pad()) {
                    continue;
                }
                int id = loopIds.get(foreach);
                boolean unguarded = segment.guard() == null;
                if (sharesCollection) {
                    m.addStatement("$T $L = $L",
                            EmitSupport.typeName(foreach.collectionTypeFqn()), sourceVar(id),
                            unguarded ? foreach.accessor() : "null");
                }
                if (foreach.pad()) {
                    if (unguarded) {
                        m.addStatement("int $L = $L", sizeVar(id), sizeOf(foreach, id, shared));
                        emitEmptyCheck(m, st, foreach, sizeVar(id));
                        m.addStatement("int $L = $T.padPow2($L)", padVar(id),
                                EmitSupport.LIGHT_BATIS_SQL, sizeVar(id));
                    } else {
                        // assigned inside the guard below; declared here so the
                        // bind pass can see it
                        m.addStatement("int $L = 0", sizeVar(id));
                        m.addStatement("int $L = 0", padVar(id));
                    }
                }
                if (unguarded) {
                    initialized.add(foreach);
                }
            }
        }
        return initialized;
    }

    private static void emitEmptyCheck(MethodSpec.Builder m, StatementModel st,
            SqlPiece.Foreach foreach, String sizeVar) {
        m.beginControlFlow("if ($L == 0)", sizeVar);
        m.addStatement("throw new $T($S, $S)", EmitSupport.EMPTY_FOREACH,
                st.statementId(), foreach.label());
        m.endControlFlow();
    }

    /**
     * Appends a run of pieces, breaking the {@code sb.append(...)} chain
     * wherever a {@code <foreach>} needs statements of its own.
     */
    private static void appendPieces(MethodSpec.Builder m, StatementModel st,
            List<SqlPiece> pieces, Map<SqlPiece.Foreach, Integer> loopIds,
            Set<SqlPiece.Foreach> alreadyInitialized, Set<SqlPiece.Foreach> shared) {
        List<SqlPiece> run = new ArrayList<>();
        for (SqlPiece piece : pieces) {
            if (piece instanceof SqlPiece.Foreach foreach) {
                flushRun(m, run);
                appendForeach(m, st, foreach, loopIds, alreadyInitialized, shared);
                continue;
            }
            run.add(piece);
        }
        flushRun(m, run);
    }

    private static void flushRun(MethodSpec.Builder m, List<SqlPiece> run) {
        if (run.isEmpty()) {
            return;
        }
        CodeBlock chain = appendChain(run);
        if (!chain.isEmpty()) {
            m.addStatement("sb$L", chain);
        }
        run.clear();
    }

    /**
     * The placeholder loop. The count is the one value-dependent
     * thing in the whole statement, so it is also the only place the emitter
     * writes a loop into the SQL assembly.
     */
    private static void appendForeach(MethodSpec.Builder m, StatementModel st,
            SqlPiece.Foreach foreach, Map<SqlPiece.Foreach, Integer> loopIds,
            Set<SqlPiece.Foreach> alreadyInitialized, Set<SqlPiece.Foreach> shared) {
        int id = loopIds.get(foreach);
        // always the synthetic name: the bind pass declares the XML's index
        // name in its own scope, and a duplicate local would not compile
        String counter = "k" + id;
        boolean assignHere = !alreadyInitialized.contains(foreach);
        if (shared.contains(foreach) && assignHere) {
            // the guarded case: declared at method scope, filled in here,
            // where the guard says the loop really runs
            m.addStatement("$L = $L", sourceVar(id), foreach.accessor());
        }
        String bound;
        if (foreach.pad()) {
            // the locals are hoisted so the bind pass can see them; a guarded
            // loop is the only one still needing its assignment here
            if (assignHere) {
                m.addStatement("$L = $L", sizeVar(id), sizeOf(foreach, id, shared));
                emitEmptyCheck(m, st, foreach, sizeVar(id));
                m.addStatement("$L = $T.padPow2($L)", padVar(id),
                        EmitSupport.LIGHT_BATIS_SQL, sizeVar(id));
            }
            bound = padVar(id);
        } else {
            m.addStatement("int $L = $L", sizeVar(id), sizeOf(foreach, id, shared));
            emitEmptyCheck(m, st, foreach, sizeVar(id));
            bound = sizeVar(id);
        }

        if (foreach.open() != null) {
            m.addStatement("sb.append($S)", foreach.open());
        }
        String bodyLiteral = literalOf(foreach.body());
        if (bodyLiteral != null) {
            // the shape: one append per element, separator folded into the
            // ternary — sb.append(k == 0 ? " ?" : " , ?"). The elements
            // themselves are not needed here; every #{} in the body is a "?".
            String separated = (foreach.separator() == null ? "" : foreach.separator())
                    + bodyLiteral;
            m.addStatement("for (int $1L = 0; $1L < $2L; $1L++) sb.append($1L == 0 ? $3S : $4S)",
                    counter, bound, bodyLiteral, separated);
        } else {
            // The SQL text depends on the elements — a nested <foreach> reads
            // its collection off the item, a ${} splices a value — so this
            // loop walks them, exactly as the bind loop will.
            m.addStatement("int $L = 0", counter);
            beginElementLoop(m, foreach, collectionOf(foreach, id, shared));
            for (SqlPiece.Foreach.Local local : foreach.locals()) {
                m.addStatement("$T $L = $L", EmitSupport.typeName(local.typeFqn()),
                        local.name(), local.initExpr());
            }
            if (foreach.counterVar() != null) {
                m.addStatement("int $L = $L", foreach.counterVar(), counter);
            }
            if (foreach.separator() != null) {
                m.beginControlFlow("if ($L > 0)", counter);
                m.addStatement("sb.append($S)", foreach.separator());
                m.endControlFlow();
            }
            appendPieces(m, st, foreach.body(), loopIds, alreadyInitialized, shared);
            m.addStatement("$L++", counter);
            m.endControlFlow();
        }
        if (foreach.close() != null) {
            m.addStatement("sb.append($S)", foreach.close());
        }
    }

    /** {@code for (T item : collection)}, or its entrySet for a map. */
    private static void beginElementLoop(MethodSpec.Builder m, SqlPiece.Foreach foreach,
            String collection) {
        m.beginControlFlow("for ($T $L : $L)",
                EmitSupport.typeName(foreach.loopVarTypeFqn()), foreach.loopVar(),
                foreach.iteration() == SqlPiece.Foreach.Iteration.MAP_ENTRY
                        ? collection + ".entrySet()"
                        : collection);
    }

    /**
     * The body as one constant string, or null when it needs statements — a
     * {@code ${}} splice or a nested {@code <foreach>} inside it.
     */
    private static String literalOf(List<SqlPiece> body) {
        StringBuilder literal = new StringBuilder();
        for (SqlPiece piece : body) {
            if (piece instanceof SqlPiece.Text text) {
                literal.append(text.sql());
            } else if (piece instanceof SqlPiece.Bind) {
                literal.append('?');
            } else {
                return null;
            }
        }
        return literal.toString();
    }

    private static String sizeVar(int loopId) {
        return "n" + loopId;
    }

    private static String padVar(int loopId) {
        return "p" + loopId;
    }

    private static String sourceVar(int loopId) {
        return "src" + loopId;
    }

    /**
     * The expression both loops of a {@code <foreach>} walk. A mapper
     * parameter is already a local and is used as it stands; a collection
     * reached through a getter becomes one, because the two loops have to see
     * the same object. {@code q.getIds()} answering with a fresh list each
     * call would put {@code n} placeholders in the SQL and bind a different
     * count against them — a mismatch no test with a well-behaved getter can
     * show.
     */
    private static String collectionOf(SqlPiece.Foreach foreach, int loopId,
            Set<SqlPiece.Foreach> shared) {
        return shared.contains(foreach) ? sourceVar(loopId) : foreach.accessor();
    }

    /** The element count, written against whatever {@link #collectionOf} settled on. */
    private static String sizeOf(SqlPiece.Foreach foreach, int loopId,
            Set<SqlPiece.Foreach> shared) {
        String collection = collectionOf(foreach, loopId, shared);
        return foreach.iteration() == SqlPiece.Foreach.Iteration.ARRAY
                ? collection + ".length"
                : collection + ".size()";
    }

    /**
     * One {@code .append(...)} chain. Literal text and {@code ?} coalesce,
     * and an {@link SqlPiece.Alt} absorbs the literals around it so the body
     * reads as one ternary per branch: {@code c0 ? " AND age >= ?" : " age >= ?"}.
     */
    private static CodeBlock appendChain(List<SqlPiece> pieces) {
        CodeBlock.Builder chain = CodeBlock.builder();
        StringBuilder literal = new StringBuilder();
        SqlPiece.Alt pending = null; // waiting to absorb the trailing literal run
        for (SqlPiece piece : pieces) {
            if (piece instanceof SqlPiece.Text text) {
                literal.append(text.sql());
                continue;
            }
            if (piece instanceof SqlPiece.Bind) {
                literal.append('?');
                continue;
            }
            if (piece instanceof SqlPiece.Alt alt) {
                if (pending != null) {
                    flushAlt(chain, pending, literal);
                }
                pending = new SqlPiece.Alt(alt.condition(),
                        literal + alt.whenTrue(), literal + alt.whenFalse());
                literal.setLength(0);
            } else if (piece instanceof SqlPiece.Dollar dollar) {
                if (pending != null) {
                    flushAlt(chain, pending, literal);
                    pending = null;
                } else if (literal.length() > 0) {
                    chain.add(".append($S)", literal.toString());
                    literal.setLength(0);
                }
                chain.add(".append($L)", switch (dollar.dollarKind()) {
                    case FRAGMENT -> dollar.accessor() + ".text()";
                    case ENUM_NAME -> dollar.accessor() + ".name()";
                    case CLOSED_VALUE -> dollar.accessor();
                    case ORDER_BY -> dollar.accessor() + "Sql";
                });
            }
        }
        if (pending != null) {
            flushAlt(chain, pending, literal);
        } else if (literal.length() > 0) {
            chain.add(".append($S)", literal.toString());
        }
        return chain.build();
    }

    private static void flushAlt(CodeBlock.Builder chain, SqlPiece.Alt alt, StringBuilder suffix) {
        chain.add(".append($L ? $S : $S)", alt.condition(),
                alt.whenTrue() + suffix, alt.whenFalse() + suffix);
        suffix.setLength(0);
    }

    /** A StringBuilder capacity that avoids growth for the largest variant. */
    private static int capacityOf(DynamicModel dyn) {
        int length = 0;
        for (DynamicModel.Segment segment : dyn.segments()) {
            for (SqlPiece piece : segment.pieces()) {
                if (piece instanceof SqlPiece.Text text) {
                    length += text.sql().length();
                } else if (piece instanceof SqlPiece.Alt alt) {
                    length += Math.max(alt.whenTrue().length(), alt.whenFalse().length());
                } else if (piece instanceof SqlPiece.Foreach foreach) {
                    // unknowable; room for a typical IN list without a regrow
                    length += 64 + (foreach.open() == null ? 0 : foreach.open().length())
                            + (foreach.close() == null ? 0 : foreach.close().length());
                } else {
                    length += piece instanceof SqlPiece.Bind ? 1 : 16;
                }
            }
        }
        return (length + 15) / 16 * 16;
    }

    private static void addBinds(MethodSpec.Builder m, StatementModel st,
            HandlerFields handlers) {
        if (st.dynamic() != null) {
            // the same condition locals now decide which parameters bind
            m.addStatement("int i = 1");
            Map<SqlPiece.Foreach, Integer> loopIds = numberForeachLoops(st.dynamic());
            Set<SqlPiece.Foreach> shared = sharedCollections(st.dynamic());
            for (DynamicModel.Segment segment : st.dynamic().segments()) {
                if (!bindsAnything(segment.pieces())) {
                    continue;
                }
                if (segment.guard() != null) {
                    m.beginControlFlow("if ($L)", segment.guard());
                }
                bindPieces(m, segment.pieces(), loopIds, handlers, shared);
                if (segment.guard() != null) {
                    m.endControlFlow();
                }
            }
            return;
        }
        int index = 1;
        for (SqlPiece piece : st.pieces()) {
            if (piece instanceof SqlPiece.Bind bind) {
                m.addStatement(EmitSupport.writeStatement(bind.kind(), index++, bind.accessor(),
                        handlers.fieldForOrNull(bind.handler())));
            }
        }
    }

    /**
     * Whether anything here needs a {@code setX} — recursively, because a
     * {@code <foreach>} whose body only splices {@code ${}} binds nothing and
     * must not produce an empty loop.
     */
    private static boolean bindsAnything(List<SqlPiece> pieces) {
        for (SqlPiece piece : pieces) {
            if (piece instanceof SqlPiece.Bind) {
                return true;
            }
            if (piece instanceof SqlPiece.Foreach foreach && bindsAnything(foreach.body())) {
                return true;
            }
        }
        return false;
    }

    private static void bindPieces(MethodSpec.Builder m, List<SqlPiece> pieces,
            Map<SqlPiece.Foreach, Integer> loopIds, HandlerFields handlers,
            Set<SqlPiece.Foreach> shared) {
        for (SqlPiece piece : pieces) {
            if (piece instanceof SqlPiece.Bind bind) {
                m.addStatement(EmitSupport.writeStatement(bind.kind(),
                        CodeBlock.of("i++"), bind.accessor(),
                        handlers.fieldForOrNull(bind.handler())));
            } else if (piece instanceof SqlPiece.Foreach foreach
                    && bindsAnything(foreach.body())) {
                bindForeach(m, foreach, loopIds, handlers, shared);
            }
        }
    }

    /**
     * The bind loop, walking the same elements in the same order as the
     * placeholder loop did — which is all the correspondence that is needed
     * — MyBatis has to route the value through
     * {@code __frch_item_0} in a HashMap and parse the SQL back out to find
     * it again; here the two loops simply run in the same order.
     */
    private static void bindForeach(MethodSpec.Builder m, SqlPiece.Foreach foreach,
            Map<SqlPiece.Foreach, Integer> loopIds, HandlerFields handlers,
            Set<SqlPiece.Foreach> shared) {
        int id = loopIds.get(foreach);
        SqlPiece.Bind padded = foreach.pad() ? soleBind(foreach.body()) : null;
        // The counter carries the XML's index name, which a sibling <foreach>
        // may use too, so it gets a block of its own rather than a mangled
        // name — the generated body still reads like the mapper.
        boolean scoped = foreach.counterVar() != null;
        if (scoped) {
            m.addCode("{\n$>");
            m.addStatement("int $L = 0", foreach.counterVar());
        }
        if (padded != null) {
            // the padded slots repeat the last bound value, so the local holds
            // exactly what was bound — not the element, which may differ when
            // the body binds a property of it
            m.addStatement("$T $L = null",
                    EmitSupport.scalarTypeName(padded.kind(), padded.enumType()).box(),
                    lastVar(id));
        }

        beginElementLoop(m, foreach, collectionOf(foreach, id, shared));
        for (SqlPiece.Foreach.Local local : foreach.locals()) {
            m.addStatement("$T $L = $L", EmitSupport.typeName(local.typeFqn()), local.name(),
                    local.initExpr());
        }
        bindPieces(m, foreach.body(), loopIds, handlers, shared);
        if (padded != null) {
            m.addStatement("$L = $L", lastVar(id), padded.accessor());
        }
        if (scoped) {
            m.addStatement("$L++", foreach.counterVar());
        }
        m.endControlFlow();

        if (padded != null) {
            // repeating the last value is invisible in an IN list, the only
            // shape @PadPow2 accepts
            m.beginControlFlow("for (int $1L = $2L; $1L < $3L; $1L++)",
                    "k" + id, sizeVar(id), padVar(id));
            m.addStatement(EmitSupport.writeStatement(padded.kind(), CodeBlock.of("i++"),
                    lastVar(id), handlers.fieldForOrNull(padded.handler())));
            m.endControlFlow();
        }
        if (scoped) {
            m.addCode("$<}\n");
        }
    }

    private static SqlPiece.Bind soleBind(List<SqlPiece> body) {
        return body.stream()
                .filter(p -> p instanceof SqlPiece.Bind)
                .map(p -> (SqlPiece.Bind) p)
                .findFirst()
                .orElse(null);
    }

    private static String lastVar(int loopId) {
        return "last" + loopId;
    }

    // --- SELECT ------------------------------------------------------------------

    private static void executeQuery(MethodSpec.Builder m, StatementModel st,
            Map<String, ResultModel> resultModels, String sqlRef) {
        m.beginControlFlow("try ($T rs = ps.executeQuery())", EmitSupport.RESULT_SET);
        if (st.scalarKind() != null) {
            scalarResult(m, st, sqlRef);
        } else {
            beanResult(m, st, resultModels, sqlRef);
        }
        m.endControlFlow();
    }

    private static void scalarResult(MethodSpec.Builder m, StatementModel st, String sqlRef) {
        CodeBlock read = EmitSupport.readExpression(st.scalarKind(), st.scalarEnumType(), "rs",
                CodeBlock.of("1"));
        if (st.returnShape() == ReturnShape.MANY) {
            TypeName element = EmitSupport.scalarTypeName(st.scalarKind(), st.scalarEnumType());
            m.addStatement("$T out = new $T<>()",
                    ParameterizedTypeName.get(EmitSupport.LIST, element.box()),
                    EmitSupport.ARRAY_LIST);
            m.beginControlFlow("while (rs.next())");
            m.addStatement("out.add($L)", read);
            m.endControlFlow();
            m.addStatement("return out");
        } else if (st.scalarKind().primitive()) {
            m.beginControlFlow("if (rs.next())");
            m.addStatement("return $L", read);
            m.endControlFlow();
            m.addStatement("throw new $T($S, $L)", EmitSupport.LIGHT_BATIS_EXCEPTION,
                    "Statement " + st.statementId()
                            + " returned no row but the method returns a primitive", sqlRef);
        } else {
            m.addStatement("return rs.next() ? $L : null", read);
        }
    }

    private static void beanResult(MethodSpec.Builder m, StatementModel st,
            Map<String, ResultModel> resultModels, String sqlRef) {
        ResultModel result = resultModels.get(st.resultFqn());
        if (st.nested() != null) {
            nestedBeanResult(m, st, result, resultModels.get(st.nested().childFqn()), sqlRef);
            return;
        }
        ClassName reader = ClassName.get(result.packageName(), result.readerSimpleName());
        ClassName resultClass = ClassName.bestGuess(result.fqn());
        ReaderAccess access = st.readerAccess();
        CodeBlock read = readCall(reader, access, "COLS_" + st.methodName(), "cols");
        if (st.returnShape() == ReturnShape.ONE) {
            if (access.isNameBased()) {
                m.addStatement("return rs.next() ? $T.read(rs, $L) : null", reader,
                        columnsCall(st, reader, access, "cols_" + st.methodName()));
            } else {
                m.addStatement("return rs.next() ? $L : null", read);
            }
            return;
        }
        m.addStatement("$T out = new $T<>()",
                ParameterizedTypeName.get(EmitSupport.LIST, resultClass), EmitSupport.ARRAY_LIST);
        if (access.isNameBased()) {
            // indexes resolved once, on the first row
            m.addStatement("int[] cols = null");
            m.beginControlFlow("while (rs.next())");
            m.beginControlFlow("if (cols == null)");
            m.addStatement("cols = $L", columnsCall(st, reader, access, "cols_" + st.methodName()));
            m.endControlFlow();
        } else {
            m.beginControlFlow("while (rs.next())");
        }
        m.addStatement("out.add($L)", read);
        m.endControlFlow();
        m.addStatement("return out");
    }

    /** {@code Row.read(rs)} / {@code Row.read(rs, COLS_x)} / {@code Row.read(rs, cols)}. */
    private static CodeBlock readCall(ClassName reader, ReaderAccess access, String constant,
            String local) {
        return switch (access.mode()) {
            case POSITIONAL_CANONICAL -> CodeBlock.of("$T.read(rs)", reader);
            case POSITIONAL_CUSTOM -> CodeBlock.of("$T.read(rs, $L)", reader, constant);
            case NAME_BASED, NAME_BASED_MAPPED -> CodeBlock.of("$T.read(rs, $L)", reader, local);
        };
    }

    /**
     * Where the name-based positions come from: the reader's own
     * property-name matching, or the per-statement resolver a
     * {@code <resultMap>} needed because it named the columns itself.
     */
    private static CodeBlock columnsCall(StatementModel st, ClassName reader, ReaderAccess access,
            String resolver) {
        return access.mode() == ReaderAccess.Mode.NAME_BASED_MAPPED
                ? CodeBlock.of("$L(rs)", resolver)
                : CodeBlock.of("$T.columns(rs)", reader);
    }

    /**
     * The grouping loop of a one-level nested result map.
     * The ResultSet arrives ordered by the parent key, so a new parent starts
     * exactly where the key changes — which is why this is a loop and not a
     * map keyed by identity.
     *
     * <p>MyBatis builds a {@code CacheKey} per row for this: reflect over the
     * result map's id columns, read each value through its TypeHandler, hash
     * them together, and look the parent up in a map. Here the key columns are
     * known at build time, so they are read into typed locals and compared
     * directly — no hashing, no map, no boxing for a primitive key.
     */
    private static void nestedBeanResult(MethodSpec.Builder m, StatementModel st,
            ResultModel parent, ResultModel child, String sqlRef) {
        NestedResult nested = st.nested();
        ClassName parentClass = ClassName.bestGuess(parent.fqn());
        ClassName childClass = ClassName.bestGuess(child.fqn());
        ClassName parentReader = ClassName.get(parent.packageName(), parent.readerSimpleName());
        ClassName childReader = ClassName.get(child.packageName(), child.readerSimpleName());
        ReaderAccess parentAccess = st.readerAccess();
        ReaderAccess childAccess = nested.childAccess();
        boolean collection = nested.kind() == NestedResult.Kind.COLLECTION;

        m.addStatement("$T out = new $T<>()",
                ParameterizedTypeName.get(EmitSupport.LIST, parentClass), EmitSupport.ARRAY_LIST);
        m.addStatement("$T parent = null", parentClass);
        if (collection) {
            m.addStatement("$T nested = null",
                    ParameterizedTypeName.get(EmitSupport.LIST, childClass));
        }
        for (int i = 0; i < nested.parentKeys().size(); i++) {
            NestedResult.KeyProperty key = nested.parentKeys().get(i);
            m.addStatement("$T $L = $L", EmitSupport.scalarTypeName(key.kind(), key.enumType()),
                    "pk" + i, EmitSupport.defaultLiteral(key.kind()));
        }
        if (parentAccess.isNameBased()) {
            m.addStatement("int[] cols = null");
        }
        if (childAccess.isNameBased()) {
            m.addStatement("int[] ncols = null");
        }

        m.beginControlFlow("while (rs.next())");
        if (parentAccess.isNameBased() || childAccess.isNameBased()) {
            String guard = parentAccess.isNameBased() ? "cols" : "ncols";
            m.beginControlFlow("if ($L == null)", guard);
            if (parentAccess.isNameBased()) {
                m.addStatement("cols = $L",
                        columnsCall(st, parentReader, parentAccess, "cols_" + st.methodName()));
            }
            if (childAccess.isNameBased()) {
                m.addStatement("ncols = $L",
                        columnsCall(st, childReader, childAccess, "ncols_" + st.methodName()));
            }
            // The build could not check these: with an unparseable select list
            // the key columns are only known to exist once a ResultSet is in
            // hand. Saying which column is missing beats letting getObject(0)
            // reach the driver.
            for (NestedResult.KeyProperty key : nested.parentKeys()) {
                emitKeyColumnCheck(m, st, parentAccess, key.index(), "cols", parent, sqlRef);
            }
            emitKeyColumnCheck(m, st, childAccess, nested.childKey().index(), "ncols", child,
                    sqlRef);
            m.endControlFlow();
        }

        // the key of the row in hand, read once and reused by the comparison
        // and by the assignment that opens the next group
        CodeBlock.Builder differs = CodeBlock.builder();
        for (int i = 0; i < nested.parentKeys().size(); i++) {
            NestedResult.KeyProperty key = nested.parentKeys().get(i);
            m.addStatement("$T $L = $L", EmitSupport.scalarTypeName(key.kind(), key.enumType()),
                    "rk" + i, EmitSupport.readExpression(key.kind(), key.enumType(), "rs",
                            columnOf(parentAccess, key.index(), "cols")));
            differs.add(i == 0 ? "$L" : " || $L", key.kind().primitive()
                    ? CodeBlock.of("rk$L != pk$L", i, i)
                    : CodeBlock.of("!$T.equals(rk$L, pk$L)", ClassName.get(Objects.class), i, i));
        }

        m.beginControlFlow("if (parent == null || $L)", differs.build());
        m.addStatement("parent = $L",
                readCall(parentReader, parentAccess, "COLS_" + st.methodName(), "cols"));
        if (collection) {
            m.addStatement("nested = new $T<>()", EmitSupport.ARRAY_LIST);
            m.addStatement("parent.$L(nested)", nested.setterName());
        }
        m.addStatement("out.add(parent)");
        for (int i = 0; i < nested.parentKeys().size(); i++) {
            m.addStatement("pk$1L = rk$1L", i);
        }
        if (!collection) {
            // an <association> is set once per parent; a LEFT JOIN miss leaves
            // it null, which is the only thing a missing row can mean
            beginChildPresent(m, nested, childAccess);
            m.addStatement("parent.$L($L)", nested.setterName(),
                    readCall(childReader, childAccess, "NCOLS_" + st.methodName(), "ncols"));
            m.endControlFlow();
        }
        m.endControlFlow();

        if (collection) {
            beginChildPresent(m, nested, childAccess);
            m.addStatement("nested.add($L)",
                    readCall(childReader, childAccess, "NCOLS_" + st.methodName(), "ncols"));
            m.endControlFlow();
        }
        m.endControlFlow();

        if (st.returnShape() == ReturnShape.ONE) {
            m.addStatement("return out.isEmpty() ? null : out.get(0)");
        } else {
            m.addStatement("return out");
        }
    }

    /** Guards one resolved key position; a no-op unless the mode is name-based. */
    private static void emitKeyColumnCheck(MethodSpec.Builder m, StatementModel st,
            ReaderAccess access, int propertyIndex, String local, ResultModel result,
            String sqlRef) {
        if (!access.isNameBased()) {
            return;
        }
        String column = access.mode() == ReaderAccess.Mode.NAME_BASED_MAPPED
                ? access.columnNames().get(propertyIndex)
                : result.properties().get(propertyIndex).name();
        m.beginControlFlow("if ($L[$L] == 0)", local, propertyIndex);
        m.addStatement("throw new $T($S, $L)", EmitSupport.LIGHT_BATIS_EXCEPTION,
                "Statement " + st.statementId() + ": the <resultMap> key column \"" + column
                        + "\" is not in the ResultSet, so rows cannot be grouped", sqlRef);
        m.endControlFlow();
    }

    /**
     * The LEFT JOIN test. {@code getObject} rather than a typed getter because
     * the question is only whether the column is NULL, and a typed getter
     * would have to be followed by {@code wasNull()} anyway.
     */
    private static void beginChildPresent(MethodSpec.Builder m, NestedResult nested,
            ReaderAccess childAccess) {
        m.beginControlFlow("if (rs.getObject($L) != null)",
                columnOf(childAccess, nested.childKey().index(), "ncols"));
    }

    /**
     * Where one property's column sits: a literal when the generator knows the
     * select list, an index into the resolved array when it does not. One
     * source of truth for all four reader modes.
     */
    private static CodeBlock columnOf(ReaderAccess access, int propertyIndex, String local) {
        return switch (access.mode()) {
            case POSITIONAL_CANONICAL -> CodeBlock.of("$L", propertyIndex + 1);
            case POSITIONAL_CUSTOM -> CodeBlock.of("$L", access.columnOrder().get(propertyIndex));
            case NAME_BASED, NAME_BASED_MAPPED -> CodeBlock.of("$L[$L]", local, propertyIndex);
        };
    }

    /**
     * A {@code Stream}-returning body. The only generated
     * shape whose JDBC resources outlive the method: the Connection, the
     * statement and the ResultSet are handed to the stream, and closing the
     * stream is what gives them back.
     *
     * <p>So this body has no {@code finally} — a {@code release(c)} there
     * would close the cursor the caller is about to read. The failure path
     * undoes by hand instead, through {@code s.streamFailed}, which also
     * suppresses a cleanup failure into the real one.
     *
     * <p>Both failure arms are caught, not just the SQL one. Binding
     * {@code #{user.name}} against a null bean throws an NPE between
     * {@code conn()} and the hand-off, and with only a {@code SQLException}
     * arm that NPE would carry the Connection, the statement and the cursor
     * out of the method with nothing left to release them.
     */
    private static void streamBody(MethodSpec.Builder m, StatementModel st,
            Map<String, ResultModel> resultModels, String sqlRef, HandlerFields handlers) {
        m.addStatement("$T c = s.conn()", EmitSupport.CONNECTION);
        m.addStatement("$T ps = null", EmitSupport.PREPARED_STATEMENT);
        m.addStatement("$T rs = null", EmitSupport.RESULT_SET);
        m.beginControlFlow("try");
        m.addStatement("ps = c.prepareStatement($L)", sqlRef);
        addBinds(m, st, handlers);
        m.addStatement("rs = ps.executeQuery()");
        // built first: the name-based case adds an `int[] cols = ...` line of
        // its own, which has to land between executeQuery() and the return
        CodeBlock reader = rowReaderExpression(m, st, resultModels);
        m.addStatement("return s.stream(c, ps, rs, $L, $L)", reader, sqlRef);
        m.nextControlFlow("catch ($T e)", EmitSupport.SQL_EXCEPTION);
        m.addStatement("throw s.streamFailed(c, ps, rs, $L, e)", sqlRef);
        m.nextControlFlow("catch ($T e)", EmitSupport.RUNTIME_EXCEPTION);
        m.addStatement("throw s.streamFailed(c, ps, rs, $L, e)", sqlRef);
        m.endControlFlow();
    }

    /**
     * The {@link io.github.larkbatis.processor.ir.ReaderAccess} of the
     * statement as a {@code RowReader}: a method reference when the positions
     * are canonical, a lambda closing over the positions otherwise. The
     * name-based case resolves its indexes eagerly — {@code getMetaData()}
     * works before the first row, and a stream has no "first row" to hang the
     * lazy resolution on.
     */
    private static CodeBlock rowReaderExpression(MethodSpec.Builder m, StatementModel st,
            Map<String, ResultModel> resultModels) {
        if (st.scalarKind() != null) {
            return CodeBlock.of("r -> $L", EmitSupport.readExpression(st.scalarKind(),
                    st.scalarEnumType(), "r", CodeBlock.of("1")));
        }
        ResultModel result = resultModels.get(st.resultFqn());
        ClassName reader = ClassName.get(result.packageName(), result.readerSimpleName());
        return switch (st.readerAccess().mode()) {
            case POSITIONAL_CANONICAL -> CodeBlock.of("$T::read", reader);
            case POSITIONAL_CUSTOM -> CodeBlock.of("r -> $T.read(r, $L)", reader,
                    "COLS_" + st.methodName());
            case NAME_BASED, NAME_BASED_MAPPED -> {
                m.addStatement("int[] cols = $L", columnsCall(st, reader, st.readerAccess(),
                        "cols_" + st.methodName()));
                yield CodeBlock.of("r -> $T.read(r, cols)", reader);
            }
        };
    }

    // --- INSERT / UPDATE / DELETE ---------------------------------------------------

    private static void executeUpdate(MethodSpec.Builder m, StatementModel st, String sqlRef) {
        if (st.keys() == null) {
            returnCount(m, st.returnTypeFqn(), CodeBlock.of("ps.executeUpdate()"));
            return;
        }
        boolean isVoid = st.returnTypeFqn().equals("void");
        if (isVoid) {
            m.addStatement("ps.executeUpdate()");
        } else {
            m.addStatement("int n = ps.executeUpdate()");
        }
        m.beginControlFlow("try ($T gk = ps.getGeneratedKeys())", EmitSupport.RESULT_SET);
        m.beginControlFlow("if (gk.next())");
        assignKeys(m, st.keys(), "gk");
        // A driver that returns no key row leaves keyProperty at 0 or null,
        // and the caller finds out at the next foreign key. The batch path
        // has always refused to let that pass; this is the same refusal for
        // one row. INSERT ... ON DUPLICATE KEY UPDATE landing on the update
        // branch is the case that reaches it in production.
        m.nextControlFlow("else");
        m.addStatement("throw new $T($S)", EmitSupport.NO_KEY, st.statementId());
        m.endControlFlow();
        m.endControlFlow();
        if (!isVoid) {
            returnCount(m, st.returnTypeFqn(), CodeBlock.of("n"));
        }
    }

    private static void executeBatch(MethodSpec.Builder m, StatementModel st) {
        if (st.keys() == null) {
            returnCount(m, st.returnTypeFqn(),
                    CodeBlock.of("$T.sum(ps.executeBatch())", EmitSupport.LIGHT_BATIS_SQL));
            return;
        }
        String list = st.batch().paramName();
        boolean isVoid = st.returnTypeFqn().equals("void");
        if (isVoid) {
            m.addStatement("ps.executeBatch()");
        } else {
            m.addStatement("int n = $T.sum(ps.executeBatch())", EmitSupport.LIGHT_BATIS_SQL);
        }
        m.beginControlFlow("try ($T gk = ps.getGeneratedKeys())", EmitSupport.RESULT_SET);
        m.addStatement("int i = 0");
        m.beginControlFlow("while (gk.next() && i < $L.size())", list);
        assignKeys(m, st.keys(), "gk");
        m.addStatement("i++");
        m.endControlFlow();
        // fewer keys than rows would silently leave null ids (MyBatis #1523)
        m.beginControlFlow("if (i != $L.size())", list);
        m.addStatement("throw new $T($S, $L.size(), i)", EmitSupport.KEY_COUNT_MISMATCH,
                st.statementId(), list);
        m.endControlFlow();
        m.endControlFlow();
        if (!isVoid) {
            returnCount(m, st.returnTypeFqn(), CodeBlock.of("n"));
        }
    }

    private static void assignKeys(MethodSpec.Builder m, KeyModel keys, String resultSetVar) {
        int position = 1;
        for (KeyModel.Assignment assignment : keys.assignments()) {
            // key read type chosen from the setter signature
            m.addStatement("$L.$L($L)", assignment.targetAccessor(), assignment.setterName(),
                    EmitSupport.readExpression(assignment.kind(), null, resultSetVar,
                            CodeBlock.of("$L", position++)));
        }
    }

    /** Adapts the raw update count to the declared return type (int/long/boolean/void). */
    private static void returnCount(MethodSpec.Builder m, String returnTypeFqn, CodeBlock count) {
        switch (returnTypeFqn) {
            case "void" -> m.addStatement("$L", count);
            case "int", "java.lang.Integer" -> m.addStatement("return $L", count);
            case "long" -> m.addStatement("return $L", count);
            case "java.lang.Long" -> m.addStatement("return (long) $L", count);
            case "boolean", "java.lang.Boolean" -> m.addStatement("return $L > 0", count);
            default -> throw new IllegalStateException("unreachable: " + returnTypeFqn);
        }
    }

    private static void emptyBatchReturn(MethodSpec.Builder m, String returnTypeFqn) {
        switch (returnTypeFqn) {
            case "void" -> m.addStatement("return");
            case "int", "java.lang.Integer" -> m.addStatement("return 0");
            case "long", "java.lang.Long" -> m.addStatement("return 0L");
            case "boolean", "java.lang.Boolean" -> m.addStatement("return false");
            default -> throw new IllegalStateException("unreachable: " + returnTypeFqn);
        }
    }

    private static TypeName returnTypeName(StatementModel st, Map<String, ResultModel> resultModels) {
        if (st.returnShape() == ReturnShape.UPDATE_COUNT) {
            return EmitSupport.typeName(st.returnTypeFqn());
        }
        TypeName element = st.scalarKind() != null
                ? EmitSupport.scalarTypeName(st.scalarKind(), st.scalarEnumType())
                : ClassName.bestGuess(resultModels.get(st.resultFqn()).fqn());
        return switch (st.returnShape()) {
            case MANY -> ParameterizedTypeName.get(EmitSupport.LIST, element.box());
            case STREAM -> ParameterizedTypeName.get(EmitSupport.STREAM, element.box());
            default -> element;
        };
    }
}
