package io.github.larkbatis.processor.emit;

import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.CodeBlock;
import com.palantir.javapoet.FieldSpec;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.ParameterizedTypeName;
import com.palantir.javapoet.TypeSpec;
import io.github.larkbatis.processor.ir.ColumnNaming;
import io.github.larkbatis.processor.ir.PropertyModel;
import io.github.larkbatis.processor.ir.ResultModel;
import java.util.Locale;
import javax.lang.model.element.Modifier;

/**
 * Emits one row reader per result class: a positional
 * {@code read(rs)} for the canonical column order, a general
 * {@code read(rs, int[])} for reordered or partial select lists, and a
 * {@code columns(rs)} that resolves indexes from metadata once — the
 * name-based fallback. No reflection anywhere; the escape hatch reuses
 * {@code READER}.
 */
public final class RowReaderEmitter {

    private RowReaderEmitter() {
    }

    public static String emit(ResultModel result, ColumnNaming naming) {
        ClassName resultClass = ClassName.bestGuess(result.fqn());
        ClassName readerClass = ClassName.get(result.packageName(), result.readerSimpleName());
        String bean = beanVar(result);
        HandlerFields handlers = new HandlerFields();

        TypeSpec.Builder type = TypeSpec.classBuilder(result.readerSimpleName())
                .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
                .addAnnotation(EmitSupport.generatedAnnotation())
                .addJavadoc("Row reader for {@link $T} — generated by LarkBatis, do not edit.\n"
                        + "One reader per result class; the manual escape hatch\n"
                        + "reuses {@link #READER}.\n", resultClass);

        type.addField(FieldSpec.builder(
                        ParameterizedTypeName.get(EmitSupport.ROW_READER, resultClass),
                        "READER", Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                .initializer("$T::read", readerClass)
                .build());

        type.addMethod(MethodSpec.constructorBuilder().addModifiers(Modifier.PRIVATE).build());

        // canonical positional read: literal indexes, JIT-friendly
        MethodSpec.Builder canonical = MethodSpec.methodBuilder("read")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .returns(resultClass)
                .addParameter(EmitSupport.RESULT_SET, "rs")
                .addException(EmitSupport.SQL_EXCEPTION)
                .addJavadoc("Positional read — canonical column order: $L.\n", canonicalOrder(result))
                .addStatement("$T $L = new $T()", resultClass, bean, resultClass);
        int index = 1;
        for (PropertyModel property : result.properties()) {
            canonical.addStatement("$L.$L($L)", bean, property.setterName(),
                    EmitSupport.readExpression(property.kind(), property.enumType(),
                            handlers.fieldForOrNull(property.handler()), "rs",
                            CodeBlock.of("$L", index++)));
        }
        canonical.addStatement("return $L", bean);
        type.addMethod(canonical.build());

        // general read: c[k] = ResultSet position of property k, 0 = not selected
        MethodSpec.Builder general = MethodSpec.methodBuilder("read")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .returns(resultClass)
                .addParameter(EmitSupport.RESULT_SET, "rs")
                .addParameter(int[].class, "c")
                .addException(EmitSupport.SQL_EXCEPTION)
                .addJavadoc("General read: {@code c[k]} is the ResultSet position of property"
                        + " {@code k}, 0 = not selected.\n")
                .addStatement("$T $L = new $T()", resultClass, bean, resultClass);
        for (int k = 0; k < result.properties().size(); k++) {
            PropertyModel property = result.properties().get(k);
            general.beginControlFlow("if (c[$L] != 0)", k)
                    .addStatement("$L.$L($L)", bean, property.setterName(),
                            EmitSupport.readExpression(property.kind(), property.enumType(),
                                    handlers.fieldForOrNull(property.handler()), "rs",
                                    CodeBlock.of("c[$L]", k)))
                    .endControlFlow();
        }
        general.addStatement("return $L", bean);
        type.addMethod(general.build());

        // name-based fallback: resolve indexes once per ResultSet. Which
        // labels match which property was decided at build time, so the switch
        // normalizes the label exactly as far as the chosen convention does.
        MethodSpec.Builder columns = MethodSpec.methodBuilder("columns")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .returns(int[].class)
                .addParameter(EmitSupport.RESULT_SET, "rs")
                .addException(EmitSupport.SQL_EXCEPTION)
                .addJavadoc("Name-based fallback: resolves column positions from"
                        + " ResultSetMetaData once, on the first row.\n"
                        + "Unmatched columns are ignored, like MyBatis auto-mapping.\n")
                .addStatement("$T md = rs.getMetaData()", EmitSupport.RESULT_SET_META_DATA)
                .addStatement("int[] c = new int[$L]", result.properties().size())
                .beginControlFlow("for (int i = 1, n = md.getColumnCount(); i <= n; i++)")
                .beginControlFlow("switch ($L)", EmitSupport.columnLabelKey(naming, "i"));
        for (int k = 0; k < result.properties().size(); k++) {
            columns.addCode("case $S:\n$>c[$L] = i;\nbreak;\n$<",
                    result.properties().get(k).matchKey(naming), k);
        }
        columns.addCode("default:\n$>break;\n$<")
                .endControlFlow()
                .endControlFlow()
                .addStatement("return c");
        type.addMethod(columns.build());

        handlers.addTo(type);

        return JavaFile.builder(result.packageName(), type.build())
                .skipJavaLangImports(true)
                .indent("    ")
                .build()
                .toString();
    }

    private static String canonicalOrder(ResultModel result) {
        StringBuilder sb = new StringBuilder();
        for (PropertyModel property : result.properties()) {
            if (sb.length() > 0) {
                sb.append(", ");
            }
            sb.append(property.name());
        }
        return sb.toString();
    }

    private static String beanVar(ResultModel result) {
        String candidate = result.simpleName().substring(0, 1).toLowerCase(Locale.ROOT);
        return candidate.equals("c") || candidate.equals("r") ? "v" : candidate;
    }
}
