package io.github.lightbatis.processor;

import io.github.lightbatis.processor.emit.FilerSourceWriter;
import io.github.lightbatis.processor.emit.MapperImplEmitter;
import io.github.lightbatis.processor.emit.RegistryEmitter;
import io.github.lightbatis.processor.emit.RowReaderEmitter;
import io.github.lightbatis.processor.emit.SourceWriter;
import io.github.lightbatis.processor.frontend.AnnotationFrontend;
import io.github.lightbatis.processor.ir.MapperModel;
import io.github.lightbatis.processor.ir.ResultModel;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.ProcessingEnvironment;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedOptions;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.TypeElement;
import javax.tools.Diagnostic;

/**
 * The LightBatis annotation processor (build plan §05, task 5). Declared
 * {@code aggregating} for Gradle incremental processing: a result class can be
 * the resultType of several mappers and the registry spans all of them, so
 * outputs have no single originating element (build plan §01).
 *
 * <p>The XML mapper path arrives in M2 via {@code -Alightbatis.mapperDir}
 * (build plan §02); the option is declared now so builds can already pass it.
 */
@SupportedOptions({LightBatisProcessor.OPTION_MAPPER_DIR, LightBatisProcessor.OPTION_REGISTRY_PACKAGE})
public class LightBatisProcessor extends AbstractProcessor {

    public static final String OPTION_MAPPER_DIR = "lightbatis.mapperDir";
    public static final String OPTION_REGISTRY_PACKAGE = "lightbatis.registryPackage";

    private static final Set<String> STATEMENT_ANNOTATIONS = Set.of(
            "io.github.lightbatis.annotations.Select",
            "io.github.lightbatis.annotations.Insert",
            "io.github.lightbatis.annotations.Update",
            "io.github.lightbatis.annotations.Delete");

    /** One reader per result class, across every mapper and round. */
    private final Map<String, ResultModel> resultModels = new HashMap<>();
    private final Set<String> emittedReaders = new HashSet<>();
    private boolean registryEmitted;

    private AnnotationFrontend frontend;
    private SourceWriter sourceWriter;

    @Override
    public synchronized void init(ProcessingEnvironment env) {
        super.init(env);
        frontend = new AnnotationFrontend(env, resultModels);
        sourceWriter = new FilerSourceWriter(env.getFiler());
    }

    @Override
    public Set<String> getSupportedAnnotationTypes() {
        return STATEMENT_ANNOTATIONS;
    }

    @Override
    public SourceVersion getSupportedSourceVersion() {
        return SourceVersion.latestSupported();
    }

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        // deterministic order: mappers sorted by FQN
        TreeMap<String, TypeElement> mappers = new TreeMap<>();
        for (TypeElement annotation : annotations) {
            for (Element annotated : roundEnv.getElementsAnnotatedWith(annotation)) {
                Element enclosing = annotated.getEnclosingElement();
                if (enclosing instanceof TypeElement type
                        && enclosing.getKind() == ElementKind.INTERFACE) {
                    mappers.put(type.getQualifiedName().toString(), type);
                } else if (enclosing instanceof TypeElement type) {
                    processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR,
                            "LightBatis statements belong on interface methods", annotated);
                }
            }
        }
        if (mappers.isEmpty()) {
            return false;
        }

        List<MapperModel> models = new ArrayList<>();
        for (TypeElement mapper : mappers.values()) {
            MapperModel model = frontend.parse(mapper);
            if (model == null) {
                continue; // errors already reported; never emit partial code
            }
            models.add(model);
            onModel(model);
            sourceWriter.write(model.packageName() + "." + model.implSimpleName(),
                    MapperImplEmitter.emit(model, resultModels), mapper);
        }

        for (ResultModel result : new TreeMap<>(resultModels).values()) {
            if (emittedReaders.add(result.readerFqn())) {
                sourceWriter.write(result.readerFqn(), RowReaderEmitter.emit(result));
            }
        }

        if (!models.isEmpty() && !registryEmitted) {
            // emitted in the first round that sees mappers; mappers generated by
            // other processors in later rounds get impls but not registry entries
            registryEmitted = true;
            String registryPackage = processingEnv.getOptions()
                    .getOrDefault(OPTION_REGISTRY_PACKAGE, commonPackage(models));
            sourceWriter.write(registryPackage + "." + RegistryEmitter.REGISTRY_SIMPLE_NAME,
                    RegistryEmitter.emit(registryPackage, models),
                    mappers.values().toArray(new Element[0]));
        }
        return false;
    }

    /** Test hook: golden IR assertions override this to capture models. */
    protected void onModel(MapperModel model) {
    }

    private static String commonPackage(List<MapperModel> models) {
        String common = models.get(0).packageName();
        for (MapperModel model : models) {
            String candidate = model.packageName();
            while (!common.isEmpty()
                    && !(candidate.equals(common) || candidate.startsWith(common + "."))) {
                int dot = common.lastIndexOf('.');
                common = dot < 0 ? "" : common.substring(0, dot);
            }
        }
        return common.isEmpty() ? "lightbatis.generated" : common;
    }
}
