package io.github.larkbatis.scanner;

import java.io.IOException;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Pattern;

/**
 * The property types of a class a mapper names as a result.
 *
 * <p>This is the one finding a MyBatis codebase cannot show you by looking at
 * its mappers. A result class is an ordinary POJO — it imports nothing from
 * {@code org.apache.ibatis} and {@link JavaSourceScan} skips it on purpose —
 * yet a single {@code java.util.Date} field in it stops the build on the first
 * statement that returns the class. A report that lists mappers only would say
 * "clean" about a migration that cannot compile.
 *
 * <p>The check is a <b>blocklist</b>, not the generator's whitelist, and that
 * is deliberate. A textual scan cannot tell an enum from a nested bean from a
 * class of the project's own, and the first two are supported — so a whitelist
 * would report every enum in the codebase as a BLOCKER. Naming the types that
 * are certainly unsupported under-reports, which is the documented shape of
 * this tool's counts; inventing blockers is not.
 *
 * <p>For the same reason a simple name is only resolved through an actual
 * import. {@code Date} with no {@code java.util} import in sight may be a
 * class of the project's own, and guessing would put a BLOCKER on someone
 * else's correct code.
 */
final class ResultClassScan {

    /**
     * {@code private Date createdAt;} — the type and the name together, so the
     * report can say which property rather than only which type.
     *
     * <p>Fields, not setters. Every property of a DTO has a field, whether the
     * setter is written out or generated by Lombok, so reading both would only
     * report the same decision twice. {@code static} is left out of the
     * alternatives on purpose: a constant is not a mapped property, and
     * {@code serialVersionUID} would otherwise be in every report.
     */
    private static final Pattern FIELD = Pattern.compile(
            "^\\s*(?:private|protected|public)\\s+(?:final\\s+)?"
                    + "([\\w.$]+(?:\\s*<[^;]*>)?(?:\\s*\\[\\s*])*\\s+\\w+)\\s*[;=]");

    private static final Pattern IMPORT =
            Pattern.compile("^\\s*import\\s+(?:static\\s+)?([\\w.$*]+)\\s*;");

    /**
     * What to write instead, keyed by the type that cannot be moved across JDBC.
     *
     * <p>Short on purpose, and shorter than it used to be. The date and number
     * types a legacy DTO is full of — {@code java.util.Date},
     * {@code java.sql.Timestamp}/{@code Date}/{@code Time}, {@code BigInteger},
     * {@code char}/{@code Character}, and the offset-aware {@code java.time}
     * types — are all in the whitelist now, because refusing them made the
     * migration "rewrite every DTO before the mappers compile". What is left is
     * the types that are not a column at all, plus the two the generator still
     * has no strategy for. Anything here can also be kept as-is by naming a
     * {@code @Handler} for it, which is why the guidance says so.
     */
    private static final Map<String, String> UNSUPPORTED = Map.ofEntries(
            Map.entry("java.util.Calendar", "java.time.LocalDateTime or java.time.Instant"),
            Map.entry("java.util.GregorianCalendar", "java.time.LocalDateTime"),
            Map.entry("java.util.UUID", "String — MyBatis has no UUID handler either"),
            Map.entry("java.util.Map", "a property per column"),
            Map.entry("java.util.HashMap", "a property per column"),
            Map.entry("java.util.LinkedHashMap", "a property per column"),
            Map.entry("java.util.TreeMap", "a property per column"),
            Map.entry("java.util.Set", "java.util.List, for a <collection>"),
            Map.entry("java.util.HashSet", "java.util.List, for a <collection>"),
            Map.entry("java.util.LinkedHashSet", "java.util.List, for a <collection>"),
            Map.entry("java.util.TreeSet", "java.util.List, for a <collection>"),
            Map.entry("java.util.Optional", "the property's own type, left null when absent"));

    private ResultClassScan() {
    }

    static List<Finding> scan(Path file, String fqn) throws IOException {
        return scan(SourceText.ofJava(file), fqn);
    }

    static List<Finding> scan(SourceText source, String fqn) {
        Map<String, String> imports = importsOf(source);
        List<Finding> findings = new ArrayList<>();
        for (SourceText.Match match : source.matches(FIELD)) {
            String declared = match.group();
            if (declared == null) {
                continue;
            }
            String replacement = unsupportedReplacement(typeOf(declared), imports);
            if (replacement != null) {
                findings.add(new Finding(source.file(), match.line(),
                        Rule.UNSUPPORTED_PROPERTY_TYPE, fqn,
                        normalise(declared) + " — use " + replacement));
            }
        }
        return findings;
    }

    /**
     * The type half of {@code Map<String, String> attributes}. The name is the
     * last whitespace-separated token, and generics are the reason this is a
     * last-index search rather than a split.
     */
    private static String typeOf(String declaration) {
        String trimmed = declaration.strip();
        int lastSpace = trimmed.lastIndexOf(' ');
        return lastSpace < 0 ? trimmed : trimmed.substring(0, lastSpace).trim();
    }

    /** Collapses the whitespace a declaration may carry inside its generics. */
    private static String normalise(String declaration) {
        return declaration.strip().replaceAll("\\s+", " ");
    }

    /**
     * The replacement to suggest, or null when the type is supported, is a
     * nested-mapping target, or cannot be resolved from this file alone.
     */
    private static String unsupportedReplacement(String declared, Map<String, String> imports) {
        String raw = declared.trim();
        int generics = raw.indexOf('<');
        String bare = (generics < 0 ? raw : raw.substring(0, generics)).trim();
        if (bare.endsWith("]")) {
            return null; // arrays: byte[] is supported, anything else is not a column
        }
        String resolved = bare.indexOf('.') > 0 ? bare : imports.get(bare);
        return resolved == null ? null : UNSUPPORTED.get(resolved);
    }

    /**
     * Simple name to fully-qualified name. A wildcard import contributes every
     * name this scan knows about in that package, which is what makes
     * {@code import java.util.*;} plus {@code private Date d;} resolvable
     * without a class path.
     */
    private static Map<String, String> importsOf(SourceText source) {
        Map<String, String> imports = new HashMap<>();
        for (SourceText.Match match : source.matches(IMPORT)) {
            String imported = match.group();
            if (imported == null) {
                continue;
            }
            if (imported.endsWith(".*")) {
                String packageName = imported.substring(0, imported.length() - 2);
                for (String candidate : UNSUPPORTED.keySet()) {
                    if (candidate.startsWith(packageName + ".")
                            && candidate.indexOf('.', packageName.length() + 1) < 0) {
                        imports.putIfAbsent(simpleNameOf(candidate), candidate);
                    }
                }
            } else {
                imports.put(simpleNameOf(imported), imported);
            }
        }
        // java.lang is imported by the language itself
        imports.putIfAbsent("Character", "java.lang.Character");
        return imports;
    }

    private static String simpleNameOf(String fqn) {
        return fqn.substring(fqn.lastIndexOf('.') + 1);
    }
}
