package com.example.lbsample;

import io.github.larkbatis.runtime.JdbcLarkBatisSession;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

/**
 * {@code @Column} and {@code @LarkBatisRow} against real JDBC. The processor
 * tests assert on emitted text; this asserts the emitted text reads the right
 * columns out of a real driver, which is the claim that matters.
 */
class ColumnAndRowAnnotationEndToEndTest {

    private JdbcLarkBatisSession session;
    private ContactMapper mapper;

    @BeforeEach
    void setUp() throws SQLException {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:col_" + System.nanoTime() + ";DB_CLOSE_DELAY=-1");
        try (Connection c = dataSource.getConnection(); Statement st = c.createStatement()) {
            st.execute("CREATE TABLE contacts ("
                    + "contact_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "usr_email VARCHAR(100), "
                    + "mobile VARCHAR(40))");
        }
        session = new JdbcLarkBatisSession(dataSource);
        mapper = LarkBatisMappers.contactMapper(session);
    }

    private Contact insert(String email, String phone) {
        Contact c = new Contact();
        c.setEmail(email);
        c.setPhone(phone);
        assertEquals(1, mapper.insert(c));
        return c;
    }

    /** Positional path: the select list names the declared columns, in declaration order. */
    @Test
    void declaredColumnsRoundTripThroughThePositionalReader() {
        Contact ada = insert("ada@example.com", "+84 900 000 001");

        Contact found = mapper.findById(ada.getId());
        assertEquals(ada.getId(), found.getId());
        assertEquals("ada@example.com", found.getEmail());
        assertEquals("+84 900 000 001", found.getPhone());
    }

    /** Name-based path: SELECT * matches labels against the @Column names, not the properties. */
    @Test
    void declaredColumnsAlsoMatchTheNameBasedReader() {
        insert("ada@example.com", "+84 900 000 001");
        insert("grace@example.org", "+84 900 000 002");

        List<Contact> all = mapper.all();
        assertEquals(2, all.size());
        assertEquals("ada@example.com", all.get(0).getEmail());
        assertEquals("+84 900 000 002", all.get(1).getPhone());
    }

    /** The escape hatch reading into a class no statement returns. */
    @Test
    void theEscapeHatchReadsIntoALarkBatisRowClass() {
        insert("ada@example.com", "+84 900 000 001");
        insert("grace@example.com", "+84 900 000 002");
        insert("alan@example.org", "+84 900 000 003");

        List<DomainCount> counts = mapper.countByDomain(session, 2);
        assertEquals(1, counts.size());
        assertEquals("example.com", counts.get(0).getDomain());
        assertEquals(2, counts.get(0).getTotal());
    }
}
