package com.example.lbsample;

import io.github.larkbatis.runtime.JdbcLarkBatisSession;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

/**
 * Dynamic SQL executing against real JDBC: every branch combination
 * of the folded <where>/<set> produces SQL that H2 actually accepts — the
 * stripped AND / trailing comma cases fail loudly here if the fold is wrong.
 */
class DynamicMapperEndToEndTest {

    private UserSearchMapper mapper;

    @BeforeEach
    void setUp() throws SQLException {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:dyn_" + System.nanoTime() + ";DB_CLOSE_DELAY=-1");
        try (Connection c = dataSource.getConnection(); Statement st = c.createStatement()) {
            st.execute("CREATE TABLE users ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "name VARCHAR(100) NOT NULL, "
                    + "email VARCHAR(100), "
                    + "created_at TIMESTAMP)");
            st.execute("INSERT INTO users (name, email, created_at) VALUES "
                    + "('Ada', 'ada@example.com', TIMESTAMP '2026-08-30 10:00:00'), "
                    + "('Alan', 'alan@example.com', TIMESTAMP '2026-08-30 11:00:00'), "
                    + "('Grace', 'grace@example.com', TIMESTAMP '2026-08-30 12:00:00')");
        }
        JdbcLarkBatisSession session = new JdbcLarkBatisSession(dataSource);
        mapper = LarkBatisMappers.userSearchMapper(session);
    }

    private static UserSearch query() {
        return new UserSearch();
    }

    @Test
    void noConditionsMeansNoWhere() {
        assertEquals(3, mapper.search(query()).size());
    }

    @Test
    void firstConditionAlone() {
        UserSearch q = query();
        q.setName("A%");
        List<User> found = mapper.search(q);
        assertEquals(2, found.size());
        assertEquals("Ada", found.get(0).getName());
    }

    @Test
    void secondConditionAloneRunsWithTheAndStripped() {
        UserSearch q = query();
        q.setEmail("grace@example.com");
        List<User> found = mapper.search(q);
        assertEquals(1, found.size());
        assertEquals("Grace", found.get(0).getName());
    }

    @Test
    void bothConditions() {
        UserSearch q = query();
        q.setName("A%");
        q.setEmail("alan@example.com");
        assertEquals(1, mapper.search(q).size());
    }

    @Test
    void setStripsTheTrailingCommaInEveryCombination() {
        UserSearch first = query();
        first.setId(1);
        first.setName("Ada Lovelace");
        assertEquals(1, mapper.rename(first));

        UserSearch second = query();
        second.setId(2);
        second.setEmail("alan@computing.org");
        assertEquals(1, mapper.rename(second));

        UserSearch both = query();
        both.setId(3);
        both.setName("Grace Hopper");
        both.setEmail("grace@navy.mil");
        assertEquals(1, mapper.rename(both));

        UserSearch renamed = query();
        renamed.setName("% %");
        assertEquals(2, mapper.search(renamed).size());
    }
}
