package com.example.lbsample;

import io.github.larkbatis.runtime.JdbcLarkBatisSession;
import io.github.larkbatis.runtime.LarkBatisEmptyForeachException;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.Instant;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * {@code <foreach>} executing against real JDBC. The
 * placeholder loop and the bind loop are written separately by the generator,
 * so what this proves is that they agree — H2 rejects any mismatch between
 * the number of {@code ?} and the number of bound values.
 */
class ForeachMapperEndToEndTest {

    private UserBatchMapper mapper;

    @BeforeEach
    void setUp() throws SQLException {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:foreach_" + System.nanoTime() + ";DB_CLOSE_DELAY=-1");
        try (Connection c = dataSource.getConnection(); Statement st = c.createStatement()) {
            st.execute("CREATE TABLE users ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "name VARCHAR(100) NOT NULL, "
                    + "email VARCHAR(100), "
                    + "created_at TIMESTAMP)");
            st.execute("INSERT INTO users (id, name, email, created_at) VALUES "
                    + "(1, 'Ada', 'ada@example.com', TIMESTAMP '2026-08-30 10:00:00'), "
                    + "(2, 'Alan', 'alan@example.com', TIMESTAMP '2026-08-30 11:00:00'), "
                    + "(3, 'Grace', 'grace@example.com', TIMESTAMP '2026-08-30 12:00:00')");
            // ids are seeded explicitly so the tests can name them; the
            // identity sequence has to skip past them
            st.execute("ALTER TABLE users ALTER COLUMN id RESTART WITH 4");
        }
        mapper = LarkBatisMappers.userBatchMapper(new JdbcLarkBatisSession(dataSource));
    }

    // --- cardinality: the edge cases ------------------------------------------

    @Test
    void singleElement() {
        List<User> found = mapper.findByIds(List.of(2L));
        assertEquals(1, found.size());
        assertEquals("Alan", found.get(0).getName());
    }

    @Test
    void manyElements() {
        assertEquals(List.of("Ada", "Grace"),
                mapper.findByIds(List.of(1L, 3L)).stream().map(User::getName).toList());
    }

    @Test
    void allElements() {
        assertEquals(3, mapper.findByIds(List.of(1L, 2L, 3L)).size());
    }

    /**
     * MyBatis contributes nothing for an empty collection — not even
     * {@code open}/{@code close} — leaving {@code ... WHERE id IN} for the
     * database to reject. LarkBatis fails here instead, naming the parameter.
     */
    @Test
    void emptyCollectionFailsWithTheParameterName() {
        LarkBatisEmptyForeachException thrown = assertThrows(
                LarkBatisEmptyForeachException.class, () -> mapper.findByIds(List.of()));
        assertTrue(thrown.getMessage().contains("collection=\"ids\""), thrown.getMessage());
        assertTrue(thrown.getMessage().contains("findByIds"), thrown.getMessage());
    }

    @Test
    void nullCollectionFailsLikeMyBatisDoes() {
        // ExpressionEvaluator.evaluateIterable throws on null with the default
        // nullableOnForEach=false; here it is a plain NPE at the size call
        assertThrows(NullPointerException.class, () -> mapper.findByIds(null));
    }

    // --- the four iteration shapes ------------------------------------------------

    @Test
    void arrayCollection() {
        assertEquals(List.of("Ada", "Alan"),
                mapper.findByNames(new String[] {"Ada", "Alan"}).stream()
                        .map(User::getName).toList());
    }

    /** {@code index} is the position, bound as an int — no {@code __frch_} names. */
    @Test
    void indexBindsThePosition() {
        assertEquals(List.of("Grace", "Ada"),
                mapper.findByIdsOrdered(List.of(3L, 1L)).stream().map(User::getName).toList());
    }

    /** Map iteration: key to {@code index}, value to {@code item} (issue #709). */
    @Test
    void mapEntryIteration() {
        Map<String, String> filters = new LinkedHashMap<>();
        filters.put("Ada", "ada@example.com");
        filters.put("Grace", "nope@example.com");

        assertEquals(List.of("Ada"),
                mapper.findByColumnValues(filters).stream().map(User::getName).toList());
    }

    /**
     * LarkBatis imposes no cardinality limit of its own — the loop simply
     * runs — so what bounds an {@code IN} list is the driver's or the
     * database's parameter limit (Oracle's 1000 expressions, PostgreSQL's
     * 65535 bind parameters). This pins that a large list still assembles and
     * binds correctly; exceeding a real driver's limit surfaces as that
     * driver's own error, translated through {@code s.translate}.
     */
    @Test
    void largeCardinality() {
        List<Long> ids = java.util.stream.LongStream.rangeClosed(1, 2000).boxed().toList();

        List<User> found = mapper.findByIds(ids);

        assertEquals(3, found.size(), "only three of the 2000 ids exist");
    }

    /** Nested loops: the outer element is the inner loop's collection. */
    @Test
    void nestedForeach() {
        assertEquals(List.of("Ada", "Grace"),
                mapper.findByIdGroups(List.of(List.of(1L), List.of(3L))).stream()
                        .map(User::getName).toList());
    }

    @Test
    void nestedForeachWithOneGroup() {
        assertEquals(2, mapper.findByIdGroups(List.of(List.of(1L, 2L))).size());
    }

    /** Two loops in one statement whose {@code index} share a name. */
    @Test
    void siblingLoopsSharingAnIndexName() {
        assertEquals(List.of("Grace", "Ada"),
                mapper.siblingIndexNames(List.of(3L, 1L), List.of("Grace", "Ada")).stream()
                        .map(User::getName).toList());
    }

    /** Padding where the bind is a property of the element, not the element. */
    @Test
    void paddedPropertyBind() {
        User probe = new User();
        probe.setEmail("ada@example.com");
        User other = new User();
        other.setEmail("grace@example.com");

        assertEquals(List.of("Ada", "Grace"),
                mapper.findByEmails(List.of(probe, other)).stream()
                        .map(User::getName).toList());
    }

    /**
     * The property padding has to hold at every cardinality: the extra
     * placeholders repeat the last element, so the padded query must return
     * exactly what the unpadded one does. 1..8 elements covers both exact
     * powers of two and every amount of padding in between.
     */
    @Test
    void paddingNeverChangesTheResult() {
        for (int size = 1; size <= 8; size++) {
            List<Long> ids = java.util.stream.LongStream.rangeClosed(1, size).boxed().toList();

            assertEquals(mapper.findByIds(ids).stream().map(User::getName).toList(),
                    mapper.findByIdsPadded(ids).stream().map(User::getName).toList(),
                    "padded result differs at cardinality " + size);
        }
    }

    /** ${} inside the body: the loop walks the elements to splice them. */
    @Test
    void spliceInsideTheLoop() {
        assertEquals(3, mapper.countByColumns(List.of(
                io.github.larkbatis.runtime.SqlFragment.identifier("name"),
                io.github.larkbatis.runtime.SqlFragment.identifier("email"))).size());
    }

    // --- writes --------------------------------------------------------------------

    @Test
    void multiRowInsertBuildsOneValuesList() {
        int inserted = mapper.insertAll(List.of(
                user("Barbara", "barbara@example.com"),
                user("Katherine", "katherine@example.com")));

        assertEquals(2, inserted);
        assertEquals(5, mapper.findByIds(List.of(1L, 2L, 3L, 4L, 5L)).size());
    }

    @Test
    void foreachAlongsideAnotherParameter() {
        assertEquals(2, mapper.deleteByIds(List.of(1L, 2L, 3L), "Grace"));
        assertEquals(List.of("Grace"),
                mapper.findByIds(List.of(1L, 2L, 3L)).stream().map(User::getName).toList());
    }

    // --- padding --------------------------------------------------------

    /**
     * Padding repeats the last element, which an {@code IN} list cannot
     * notice: three ids and four placeholders select the same three rows.
     */
    @Test
    void paddedQueryReturnsTheSameRows() {
        assertEquals(mapper.findByIds(List.of(1L, 2L, 3L)).size(),
                mapper.findByIdsPadded(List.of(1L, 2L, 3L)).size());
        assertEquals(1, mapper.findByIdsPadded(List.of(2L)).size());
        assertEquals(2, mapper.findByIdsPadded(List.of(1L, 3L)).size());
    }

    private static User user(String name, String email) {
        User user = new User();
        user.setName(name);
        user.setEmail(email);
        user.setCreatedAt(Instant.parse("2026-08-30T13:00:00Z"));
        return user;
    }
}
