package com.example.lbsample;

import io.github.larkbatis.runtime.JdbcLarkBatisSession;
import io.github.larkbatis.runtime.LarkBatisException;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.stream.Stream;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * {@code Stream} returns against real JDBC. Reading the rows
 * is the easy half; the half worth a test is the lifecycle — this is the only
 * generated shape whose Connection outlives the method that opened it, so
 * every assertion here is really about the connection count.
 */
class StreamMapperEndToEndTest {

    private CountingDataSource dataSource;
    private JdbcLarkBatisSession session;
    private UserMapper mapper;
    private UserSearchMapper searchMapper;

    @BeforeEach
    void setUp() throws SQLException {
        JdbcDataSource h2 = new JdbcDataSource();
        h2.setURL("jdbc:h2:mem:stream_" + System.nanoTime() + ";DB_CLOSE_DELAY=-1");
        try (Connection c = h2.getConnection(); Statement st = c.createStatement()) {
            st.execute("CREATE TABLE users ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "name VARCHAR(100) NOT NULL, "
                    + "email VARCHAR(100), "
                    + "created_at TIMESTAMP)");
            st.execute("INSERT INTO users (name, email, created_at) VALUES "
                    + "('Ada', 'ada@example.com', TIMESTAMP '2026-08-30 10:00:00'), "
                    + "('Alan', 'alan@example.com', TIMESTAMP '2026-08-30 11:00:00'), "
                    + "('Grace', 'grace@example.com', TIMESTAMP '2026-08-30 12:00:00')");
        }
        dataSource = new CountingDataSource(h2);
        session = new JdbcLarkBatisSession(dataSource);
        mapper = LarkBatisMappers.userMapper(session);
        searchMapper = LarkBatisMappers.userSearchMapper(session);
    }

    @Test
    void streamsEveryRowAndGivesTheConnectionBackOnClose() {
        assertEquals(0, dataSource.open());
        try (Stream<User> rows = mapper.streamAll()) {
            assertEquals(1, dataSource.open(), "the stream did not hold a connection");
            assertEquals(List.of("Ada", "Alan", "Grace"), rows.map(User::getName).toList());
        }
        assertEquals(0, dataSource.open(), "closing the stream did not release the connection");
    }

    @Test
    void aShortCircuitedStreamStillReleasesOnClose() {
        // findFirst leaves the cursor mid-ResultSet; close() is what matters
        try (Stream<User> rows = mapper.streamAll()) {
            assertEquals("Ada", rows.findFirst().orElseThrow().getName());
        }
        assertEquals(0, dataSource.open());
    }

    @Test
    void aScalarStreamReadsColumnOne() {
        try (Stream<String> names = mapper.streamNames()) {
            assertEquals(List.of("Ada", "Alan", "Grace"), names.toList());
        }
        assertEquals(0, dataSource.open());
    }

    @Test
    void selectStarResolvesItsIndexesBeforeTheFirstRow() {
        try (Stream<User> rows = mapper.streamStarred()) {
            assertEquals(List.of("ada@example.com", "alan@example.com", "grace@example.com"),
                    rows.map(User::getEmail).toList());
        }
        assertEquals(0, dataSource.open());
    }

    @Test
    void theEscapeHatchStreamsTheSameWay() {
        try (Stream<User> rows = mapper.streamRecent(session, 2)) {
            assertEquals(List.of("Grace", "Alan"), rows.map(User::getName).toList());
        }
        assertEquals(0, dataSource.open());
    }

    @Test
    void aFailureBeforeTheStreamExistsReleasesEverythingItself() {
        // no finally can help here — the happy path hands the resources to the
        // stream — so the catch has to undo by hand
        assertThrows(LarkBatisException.class,
                () -> mapper.streamRecent(session, -1).close());
        assertEquals(0, dataSource.open(),
                "a statement that failed before returning kept its connection");
    }

    @Test
    void aStreamInsideATransactionJoinsItAndLeavesTheConnectionToTheTransaction() {
        try (var tx = session.begin()) {
            try (Stream<User> rows = mapper.streamAll()) {
                assertEquals(3, rows.count());
            }
            // still one: release() is a no-op inside a transaction, and the
            // scope owns the connection until it ends
            assertEquals(1, dataSource.open());
            tx.commit();
        }
        assertEquals(0, dataSource.open());
    }

    /**
     * The failure that is not a {@code SQLException}. Binding {@code #{name}}
     * against a null parameter throws an NPE between {@code conn()} and the
     * hand-off, and this body has no {@code finally} to catch it in — so the
     * unchecked arm is the only thing standing between that NPE and a
     * Connection held until the pool times out.
     */
    @Test
    void anUncheckedFailureWhileBindingStillReleasesTheConnection() {
        assertThrows(NullPointerException.class, () -> searchMapper.streamByName(null));
        assertEquals(0, dataSource.open(),
                "an unchecked throw before the hand-off kept its connection");
    }

    /** The same guarantee, on the shape that always had it: nothing regressed. */
    @Test
    void aListReturnReleasesOnAnUncheckedFailureToo() {
        assertThrows(NullPointerException.class, () -> searchMapper.search(null));
        assertEquals(0, dataSource.open());
    }

    @Test
    void anUnclosedStreamKeepsTheConnection() {
        // not a recommendation — a demonstration of the contract, so the cost
        // of forgetting try-with-resources is written down somewhere executable
        Stream<User> leaked = mapper.streamAll();
        assertEquals(1, dataSource.open());
        assertTrue(leaked.findFirst().isPresent());
        assertEquals(1, dataSource.open());
        leaked.close();
        assertEquals(0, dataSource.open());
    }
}
