package com.example.lbsample;

import io.github.larkbatis.runtime.JdbcLarkBatisSession;
import java.math.BigInteger;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Time;
import java.sql.Timestamp;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.Date;
import java.util.List;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

/**
 * The widened type whitelist against a real driver, both directions.
 *
 * <p>An emitter test can only say the generated source names
 * {@code JdbcCodec.utilDate}; it cannot say the value that comes back equals
 * the value that went in. For conversions — and every type added here is a
 * conversion or a narrowing — that is the only claim worth making.
 */
class TypeWhitelistEndToEndTest {

    private static final Timestamp RECORDED = Timestamp.valueOf("2026-03-04 05:06:07");
    private static final java.sql.Date DUE = java.sql.Date.valueOf("2026-03-04");
    private static final Time ALARM = Time.valueOf("05:06:07");

    private ReadingMapper mapper;

    @BeforeEach
    void setUp() throws SQLException {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:types_" + System.nanoTime() + ";DB_CLOSE_DELAY=-1");
        try (Connection c = dataSource.getConnection(); Statement st = c.createStatement()) {
            st.execute("CREATE TABLE readings ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "taken_at TIMESTAMP, "
                    // (9) so the column can hold what a Timestamp carries and a
                    // java.util.Date cannot; H2's default is microseconds, which
                    // would round the difference away before the test sees it
                    + "recorded_at TIMESTAMP(9), "
                    + "due_on DATE, "
                    + "alarm_at TIME, "
                    + "observed_at TIMESTAMP WITH TIME ZONE, "
                    + "counter NUMERIC(40), "
                    + "grade CHAR(1), "
                    + "flag CHAR(1))");
        }
        mapper = LarkBatisMappers.readingMapper(new JdbcLarkBatisSession(dataSource));
    }

    private Reading full(Date takenAt, char grade) {
        Reading r = new Reading();
        r.setTakenAt(takenAt);
        r.setRecordedAt(RECORDED);
        r.setDueOn(DUE);
        r.setAlarmAt(ALARM);
        r.setObservedAt(OffsetDateTime.of(2026, 3, 4, 5, 6, 7, 0, ZoneOffset.ofHours(7)));
        r.setCounter(new BigInteger("123456789012345678901234567890"));
        r.setGrade(grade);
        r.setFlag('Y');
        mapper.insert(r);
        return r;
    }

    @Test
    void roundTripsEveryWidenedType() {
        Date takenAt = new Date(RECORDED.getTime());
        Reading inserted = full(takenAt, 'A');

        Reading read = mapper.find(inserted.getId());

        assertEquals(takenAt, read.getTakenAt());
        assertEquals(RECORDED, read.getRecordedAt());
        assertEquals(DUE.toString(), read.getDueOn().toString());
        assertEquals(ALARM.toString(), read.getAlarmAt().toString());
        assertEquals(new BigInteger("123456789012345678901234567890"), read.getCounter());
        assertEquals('A', read.getGrade());
        assertEquals(Character.valueOf('Y'), read.getFlag());
    }

    /**
     * The offset survives the round trip, which is the whole reason this type
     * goes through {@code getObject}/{@code setObject} rather than a Timestamp.
     */
    @Test
    void keepsTheOffsetOfAnOffsetDateTime() {
        Reading inserted = full(new Date(RECORDED.getTime()), 'A');

        OffsetDateTime read = mapper.find(inserted.getId()).getObservedAt();

        assertEquals(OffsetDateTime.of(2026, 3, 4, 5, 6, 7, 0, ZoneOffset.ofHours(7))
                .toInstant(), read.toInstant());
        assertEquals(ZoneOffset.ofHours(7), read.getOffset());
    }

    /** java.util.Date is narrowed from a Timestamp, so it must not keep the nanos. */
    @Test
    void narrowsAUtilDateToMillisecondsLikeMyBatis() {
        Timestamp withNanos = Timestamp.valueOf("2026-03-04 05:06:07.123456789");
        Reading r = new Reading();
        r.setTakenAt(new Date(withNanos.getTime()));
        r.setRecordedAt(withNanos);
        mapper.insert(r);

        Reading read = mapper.find(r.getId());

        assertEquals(withNanos.getTime(), read.getTakenAt().getTime());
        assertEquals(Date.class, read.getTakenAt().getClass(),
                "java.util.Date, not the java.sql.Date the driver would hand back");
        assertEquals(123456789, read.getRecordedAt().getNanos(),
                "the Timestamp property keeps what the util.Date one drops");
    }

    @Test
    void bindsAUtilDateAsAParameter() {
        full(new Date(Timestamp.valueOf("2020-01-01 00:00:00").getTime()), 'A');
        full(new Date(Timestamp.valueOf("2030-01-01 00:00:00").getTime()), 'B');

        List<Reading> before = mapper.takenBefore(
                new Date(Timestamp.valueOf("2025-01-01 00:00:00").getTime()));

        assertEquals(1, before.size());
        assertEquals('A', before.get(0).getGrade());
    }

    @Test
    void bindsAPrimitiveCharAsAParameter() {
        full(new Date(RECORDED.getTime()), 'A');
        full(new Date(RECORDED.getTime()), 'B');

        assertEquals(1, mapper.graded('B').size());
        assertEquals('B', mapper.graded('B').get(0).getGrade());
    }

    @Test
    void bindsABigIntegerAsAParameter() {
        full(new Date(RECORDED.getTime()), 'A');

        assertEquals(1, mapper.atLeast(new BigInteger("1")));
        assertEquals(0, mapper.atLeast(new BigInteger("999999999999999999999999999999999")));
    }

    /** Null on every nullable one: the boxed and converted kinds own setNull. */
    @Test
    void movesNullThroughEveryNullableKind() {
        Reading empty = new Reading();
        empty.setGrade('Z');
        mapper.insert(empty);

        Reading read = mapper.find(empty.getId());

        assertNull(read.getTakenAt());
        assertNull(read.getRecordedAt());
        assertNull(read.getDueOn());
        assertNull(read.getAlarmAt());
        assertNull(read.getObservedAt());
        assertNull(read.getCounter());
        assertNull(read.getFlag());
    }

    /**
     * A primitive has nowhere to put a null, and this is the bargain the
     * existing primitive getters already make — {@code rs.getInt} answers 0
     * for a NULL rather than refusing. MyBatis has no position here: it hands
     * a null Character to a primitive setter and NPEs.
     */
    @Test
    void readsANullCharColumnAsASpace() {
        Reading r = new Reading();
        r.setGrade(' ');
        mapper.insert(r);

        assertEquals(' ', mapper.find(r.getId()).getGrade());
    }
}
