package com.example.lbsample;

import io.github.larkbatis.runtime.JdbcLarkBatisSession;
import io.github.larkbatis.runtime.LarkBatisTx;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.Instant;
import java.util.List;
import org.h2.jdbcx.JdbcDataSource;

/**
 * A small application that calls
 * {@code mapper.findById(...)} and gets a {@code User} back with zero
 * reflection — the same binary is the native-image smoke-test subject.
 * No DriverManager, no Class.forName: the DataSource is constructed directly.
 */
public final class SampleApp {

    private SampleApp() {
    }

    public static void main(String[] args) throws SQLException {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:sample;DB_CLOSE_DELAY=-1");
        createSchema(dataSource);

        JdbcLarkBatisSession session = new JdbcLarkBatisSession(dataSource);
        UserMapper mapper = LarkBatisMappers.userMapper(session);

        User ada = user("Ada", "ada@example.com");
        User grace = user("Grace", "grace@example.com");
        try (LarkBatisTx tx = session.begin()) {
            mapper.insert(ada);
            mapper.insertAll(List.of(user("Edsger", null), user("Barbara", "b@example.com")));
            mapper.insert(grace);
            tx.commit();
        }

        System.out.println("findById(" + ada.getId() + ")  -> " + mapper.findById(ada.getId()));
        System.out.println("count LIKE 'G%'-> " + mapper.countByName("G%"));
        System.out.println("all(name):");
        for (User user : mapper.all("name")) {
            System.out.println("  " + user);
        }
        System.out.println("escape hatch   -> " + mapper.recent(session, 2).size() + " recent users");
    }

    private static User user(String name, String email) {
        User u = new User();
        u.setName(name);
        u.setEmail(email);
        u.setCreatedAt(Instant.now());
        return u;
    }

    private static void createSchema(JdbcDataSource dataSource) throws SQLException {
        try (Connection c = dataSource.getConnection(); Statement st = c.createStatement()) {
            st.execute("CREATE TABLE users ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "name VARCHAR(100) NOT NULL, "
                    + "email VARCHAR(100), "
                    + "created_at TIMESTAMP)");
        }
    }
}
