package io.github.lightbatis.processor.emit;

import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.CodeBlock;
import com.palantir.javapoet.FieldSpec;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.ParameterizedTypeName;
import com.palantir.javapoet.TypeName;
import com.palantir.javapoet.TypeSpec;
import io.github.lightbatis.processor.ir.KeyModel;
import io.github.lightbatis.processor.ir.MapperModel;
import io.github.lightbatis.processor.ir.ParamModel;
import io.github.lightbatis.processor.ir.ReaderAccess;
import io.github.lightbatis.processor.ir.ResultModel;
import io.github.lightbatis.processor.ir.ReturnShape;
import io.github.lightbatis.processor.ir.SqlPiece;
import io.github.lightbatis.processor.ir.StatementKind;
import io.github.lightbatis.processor.ir.StatementModel;
import io.github.lightbatis.processor.ir.ValueKind;
import java.util.Map;
import java.util.StringJoiner;
import javax.lang.model.element.Modifier;

/**
 * Emits {@code <Mapper>$$Impl} (design §04, §07, §10). The hand-written
 * landmark this must reproduce lives at
 * {@code lightbatis-runtime/src/test/java/.../handwritten/UserMapper$$Impl.java}.
 *
 * <p>Shape rules: SQL as a private static constant ({@code ?} already in
 * place); the Connection borrowed via {@code s.conn()} and returned via
 * {@code s.release(c)} in a finally — never try-with-resources (§10);
 * explicit key column names to {@code prepareStatement} (§07); every
 * SQLException through {@code s.translate(e, sql)}.
 */
public final class MapperImplEmitter {

    private MapperImplEmitter() {
    }

    public static String emit(MapperModel mapper, Map<String, ResultModel> resultModels) {
        ClassName mapperInterface = ClassName.get(mapper.packageName(), mapper.simpleName());
        TypeSpec.Builder type = TypeSpec.classBuilder(mapper.implSimpleName())
                .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
                .addSuperinterface(mapperInterface)
                .addAnnotation(EmitSupport.generatedAnnotation())
                .addJavadoc("Generated by LightBatis from {@link $T} — do not edit.\n"
                        + "Plain JDBC, resolved at build time (design §04); the only runtime"
                        + " inputs are parameter values.\n", mapperInterface);

        for (StatementModel statement : mapper.statements()) {
            addConstants(type, statement);
        }

        type.addField(EmitSupport.LIGHT_BATIS_SESSION, "s", Modifier.PRIVATE, Modifier.FINAL);
        type.addMethod(MethodSpec.constructorBuilder()
                .addModifiers(Modifier.PUBLIC)
                .addParameter(EmitSupport.LIGHT_BATIS_SESSION, "s")
                .addStatement("this.s = s")
                .build());

        for (StatementModel statement : mapper.statements()) {
            type.addMethod(method(statement, resultModels));
        }

        return JavaFile.builder(mapper.packageName(), type.build())
                .skipJavaLangImports(true)
                .indent("    ")
                .build()
                .toString();
    }

    // --- constants -------------------------------------------------------------

    private static void addConstants(TypeSpec.Builder type, StatementModel st) {
        if (st.hasDollar()) {
            type.addField(FieldSpec.builder(String.class, "STMT_" + st.methodName(),
                            Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
                    .initializer("$S", st.statementId())
                    .build());
        } else {
            type.addField(FieldSpec.builder(String.class, "SQL_" + st.methodName(),
                            Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
                    .initializer("$S", staticSql(st))
                    .build());
        }
        if (st.keys() != null && !st.keys().columns().isEmpty()) {
            CodeBlock.Builder names = CodeBlock.builder();
            for (int i = 0; i < st.keys().columns().size(); i++) {
                names.add(i == 0 ? "$S" : ", $S", st.keys().columns().get(i));
            }
            type.addField(FieldSpec.builder(String[].class, "KEYS_" + st.methodName(),
                            Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
                    .initializer("{ $L }", names.build())
                    .build());
        }
        if (st.readerAccess() != null
                && st.readerAccess().mode() == ReaderAccess.Mode.POSITIONAL_CUSTOM) {
            StringJoiner positions = new StringJoiner(", ");
            st.readerAccess().columnOrder().forEach(p -> positions.add(String.valueOf(p)));
            type.addField(FieldSpec.builder(int[].class, "COLS_" + st.methodName(),
                            Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
                    .initializer("{ $L }", positions.toString())
                    .build());
        }
    }

    /** Static SQL: literal text with {@code ?} where {@code #{}} used to be. */
    private static String staticSql(StatementModel st) {
        StringBuilder sql = new StringBuilder();
        for (SqlPiece piece : st.pieces()) {
            if (piece instanceof SqlPiece.Text t) {
                sql.append(t.sql());
            } else if (piece instanceof SqlPiece.Bind) {
                sql.append('?');
            }
        }
        return sql.toString();
    }

    // --- one method --------------------------------------------------------------

    private static MethodSpec method(StatementModel st, Map<String, ResultModel> resultModels) {
        MethodSpec.Builder m = MethodSpec.methodBuilder(st.methodName())
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .returns(returnTypeName(st, resultModels));
        for (ParamModel param : st.params()) {
            m.addParameter(EmitSupport.typeName(param.typeFqn()), param.name());
        }

        // @OrderBy switches: reject-or-accept once, reuse for SQL text (design §08)
        for (SqlPiece piece : st.pieces()) {
            if (piece instanceof SqlPiece.Dollar d
                    && d.dollarKind() == SqlPiece.Dollar.DollarKind.ORDER_BY) {
                String local = d.accessor() + "Sql";
                m.addStatement("$T $L", String.class, local);
                m.beginControlFlow("switch ($L)", d.accessor());
                for (String allowed : d.allowed()) {
                    m.addCode("case $S:\n$>$L = $S;\nbreak;\n$<", allowed, local, allowed);
                }
                CodeBlock.Builder allowedArray = CodeBlock.builder();
                for (int i = 0; i < d.allowed().size(); i++) {
                    allowedArray.add(i == 0 ? "$S" : ", $S", d.allowed().get(i));
                }
                m.addCode("default:\n$>throw new $T($L, new String[] { $L });\n$<",
                        EmitSupport.REJECTED_EXCEPTION, d.accessor(), allowedArray.build());
                m.endControlFlow();
            }
        }

        String sqlRef;
        if (st.hasDollar()) {
            sqlRef = "sql";
            m.addStatement("String sql = $L", spliceExpression(st));
            m.addStatement("$T.trackVariants($L, sql)",
                    EmitSupport.LIGHT_BATIS_SQL, "STMT_" + st.methodName());
        } else {
            sqlRef = "SQL_" + st.methodName();
        }

        if (st.batch() != null) {
            m.beginControlFlow("if ($L.isEmpty())", st.batch().paramName());
            emptyBatchReturn(m, st.returnTypeFqn());
            m.endControlFlow();
        }

        m.addStatement("$T c = s.conn()", EmitSupport.CONNECTION);
        if (st.keys() != null) {
            if (st.keys().columns().isEmpty()) {
                // build already warned: Oracle ROWID / PostgreSQL all-columns (§07)
                m.beginControlFlow("try ($T ps = c.prepareStatement($L, $T.RETURN_GENERATED_KEYS))",
                        EmitSupport.PREPARED_STATEMENT, sqlRef, EmitSupport.SQL_STATEMENT);
            } else {
                m.beginControlFlow("try ($T ps = c.prepareStatement($L, $L))",
                        EmitSupport.PREPARED_STATEMENT, sqlRef, "KEYS_" + st.methodName());
            }
        } else {
            m.beginControlFlow("try ($T ps = c.prepareStatement($L))",
                    EmitSupport.PREPARED_STATEMENT, sqlRef);
        }

        if (st.batch() != null) {
            m.beginControlFlow("for ($T $L : $L)",
                    EmitSupport.typeName(st.batch().elementTypeFqn()),
                    st.batch().loopVar(), st.batch().paramName());
            addBinds(m, st);
            m.addStatement("ps.addBatch()");
            m.endControlFlow();
            executeBatch(m, st);
        } else {
            addBinds(m, st);
            if (st.kind() == StatementKind.SELECT) {
                executeQuery(m, st, resultModels, sqlRef);
            } else {
                executeUpdate(m, st, sqlRef);
            }
        }

        m.nextControlFlow("catch ($T e)", EmitSupport.SQL_EXCEPTION);
        m.addStatement("throw s.translate(e, $L)", sqlRef);
        m.nextControlFlow("finally");
        m.addStatement("s.release(c)");
        m.endControlFlow();
        return m.build();
    }

    /** The runtime SQL expression when {@code ${}} splices are present (design §08). */
    private static CodeBlock spliceExpression(StatementModel st) {
        CodeBlock.Builder expr = CodeBlock.builder();
        StringBuilder literal = new StringBuilder();
        boolean first = true;
        for (SqlPiece piece : st.pieces()) {
            if (piece instanceof SqlPiece.Text t) {
                literal.append(t.sql());
                continue;
            }
            if (piece instanceof SqlPiece.Bind) {
                literal.append('?');
                continue;
            }
            SqlPiece.Dollar d = (SqlPiece.Dollar) piece;
            if (literal.length() > 0 || first) {
                // a leading literal also guarantees string-typed concatenation
                expr.add(first ? "$S" : " + $S", literal.toString());
                literal.setLength(0);
                first = false;
            }
            expr.add(" + $L", switch (d.dollarKind()) {
                case FRAGMENT -> d.accessor() + ".text()";
                case ENUM_NAME -> d.accessor() + ".name()";
                case CLOSED_VALUE -> d.accessor();
                case ORDER_BY -> d.accessor() + "Sql";
            });
        }
        if (literal.length() > 0 || first) {
            expr.add(first ? "$S" : " + $S", literal.toString());
        }
        return expr.build();
    }

    private static void addBinds(MethodSpec.Builder m, StatementModel st) {
        int index = 1;
        for (SqlPiece piece : st.pieces()) {
            if (piece instanceof SqlPiece.Bind bind) {
                m.addStatement(EmitSupport.writeStatement(bind.kind(), index++, bind.accessor()));
            }
        }
    }

    // --- SELECT ------------------------------------------------------------------

    private static void executeQuery(MethodSpec.Builder m, StatementModel st,
            Map<String, ResultModel> resultModels, String sqlRef) {
        m.beginControlFlow("try ($T rs = ps.executeQuery())", EmitSupport.RESULT_SET);
        if (st.scalarKind() != null) {
            scalarResult(m, st, sqlRef);
        } else {
            beanResult(m, st, resultModels.get(st.resultFqn()));
        }
        m.endControlFlow();
    }

    private static void scalarResult(MethodSpec.Builder m, StatementModel st, String sqlRef) {
        CodeBlock read = EmitSupport.readExpression(st.scalarKind(), st.scalarEnumType(), "rs",
                CodeBlock.of("1"));
        if (st.returnShape() == ReturnShape.MANY) {
            TypeName element = EmitSupport.scalarTypeName(st.scalarKind(), st.scalarEnumType());
            m.addStatement("$T out = new $T<>()",
                    ParameterizedTypeName.get(EmitSupport.LIST, element.box()),
                    EmitSupport.ARRAY_LIST);
            m.beginControlFlow("while (rs.next())");
            m.addStatement("out.add($L)", read);
            m.endControlFlow();
            m.addStatement("return out");
        } else if (st.scalarKind().primitive()) {
            m.beginControlFlow("if (rs.next())");
            m.addStatement("return $L", read);
            m.endControlFlow();
            m.addStatement("throw new $T($S, $L)", EmitSupport.LIGHT_BATIS_EXCEPTION,
                    "Statement " + st.statementId()
                            + " returned no row but the method returns a primitive", sqlRef);
        } else {
            m.addStatement("return rs.next() ? $L : null", read);
        }
    }

    private static void beanResult(MethodSpec.Builder m, StatementModel st, ResultModel result) {
        ClassName reader = ClassName.get(result.packageName(), result.readerSimpleName());
        ClassName resultClass = ClassName.bestGuess(result.fqn());
        ReaderAccess.Mode mode = st.readerAccess().mode();
        CodeBlock read = switch (mode) {
            case POSITIONAL_CANONICAL -> CodeBlock.of("$T.read(rs)", reader);
            case POSITIONAL_CUSTOM -> CodeBlock.of("$T.read(rs, $L)", reader, "COLS_" + st.methodName());
            case NAME_BASED -> CodeBlock.of("$T.read(rs, cols)", reader);
        };
        if (st.returnShape() == ReturnShape.ONE) {
            if (mode == ReaderAccess.Mode.NAME_BASED) {
                m.addStatement("return rs.next() ? $T.read(rs, $T.columns(rs)) : null", reader, reader);
            } else {
                m.addStatement("return rs.next() ? $L : null", read);
            }
            return;
        }
        m.addStatement("$T out = new $T<>()",
                ParameterizedTypeName.get(EmitSupport.LIST, resultClass), EmitSupport.ARRAY_LIST);
        if (mode == ReaderAccess.Mode.NAME_BASED) {
            // indexes resolved once, on the first row (design §04)
            m.addStatement("int[] cols = null");
            m.beginControlFlow("while (rs.next())");
            m.beginControlFlow("if (cols == null)");
            m.addStatement("cols = $T.columns(rs)", reader);
            m.endControlFlow();
        } else {
            m.beginControlFlow("while (rs.next())");
        }
        m.addStatement("out.add($L)", read);
        m.endControlFlow();
        m.addStatement("return out");
    }

    // --- INSERT / UPDATE / DELETE ---------------------------------------------------

    private static void executeUpdate(MethodSpec.Builder m, StatementModel st, String sqlRef) {
        if (st.keys() == null) {
            returnCount(m, st.returnTypeFqn(), CodeBlock.of("ps.executeUpdate()"));
            return;
        }
        boolean isVoid = st.returnTypeFqn().equals("void");
        if (isVoid) {
            m.addStatement("ps.executeUpdate()");
        } else {
            m.addStatement("int n = ps.executeUpdate()");
        }
        m.beginControlFlow("try ($T gk = ps.getGeneratedKeys())", EmitSupport.RESULT_SET);
        m.beginControlFlow("if (gk.next())");
        assignKeys(m, st.keys(), "gk");
        m.endControlFlow();
        m.endControlFlow();
        if (!isVoid) {
            returnCount(m, st.returnTypeFqn(), CodeBlock.of("n"));
        }
    }

    private static void executeBatch(MethodSpec.Builder m, StatementModel st) {
        if (st.keys() == null) {
            returnCount(m, st.returnTypeFqn(),
                    CodeBlock.of("$T.sum(ps.executeBatch())", EmitSupport.LIGHT_BATIS_SQL));
            return;
        }
        String list = st.batch().paramName();
        boolean isVoid = st.returnTypeFqn().equals("void");
        if (isVoid) {
            m.addStatement("ps.executeBatch()");
        } else {
            m.addStatement("int n = $T.sum(ps.executeBatch())", EmitSupport.LIGHT_BATIS_SQL);
        }
        m.beginControlFlow("try ($T gk = ps.getGeneratedKeys())", EmitSupport.RESULT_SET);
        m.addStatement("int i = 0");
        m.beginControlFlow("while (gk.next() && i < $L.size())", list);
        assignKeys(m, st.keys(), "gk");
        m.addStatement("i++");
        m.endControlFlow();
        // fewer keys than rows would silently leave null ids (§07, MyBatis #1523)
        m.beginControlFlow("if (i != $L.size())", list);
        m.addStatement("throw new $T($S, $L.size(), i)", EmitSupport.KEY_COUNT_MISMATCH,
                st.statementId(), list);
        m.endControlFlow();
        m.endControlFlow();
        if (!isVoid) {
            returnCount(m, st.returnTypeFqn(), CodeBlock.of("n"));
        }
    }

    private static void assignKeys(MethodSpec.Builder m, KeyModel keys, String resultSetVar) {
        int position = 1;
        for (KeyModel.Assignment assignment : keys.assignments()) {
            // key read type chosen from the setter signature (design §07)
            m.addStatement("$L.$L($L)", assignment.targetAccessor(), assignment.setterName(),
                    EmitSupport.readExpression(assignment.kind(), null, resultSetVar,
                            CodeBlock.of("$L", position++)));
        }
    }

    /** Adapts the raw update count to the declared return type (int/long/boolean/void). */
    private static void returnCount(MethodSpec.Builder m, String returnTypeFqn, CodeBlock count) {
        switch (returnTypeFqn) {
            case "void" -> m.addStatement("$L", count);
            case "int", "java.lang.Integer" -> m.addStatement("return $L", count);
            case "long" -> m.addStatement("return $L", count);
            case "java.lang.Long" -> m.addStatement("return (long) $L", count);
            case "boolean", "java.lang.Boolean" -> m.addStatement("return $L > 0", count);
            default -> throw new IllegalStateException("unreachable: " + returnTypeFqn);
        }
    }

    private static void emptyBatchReturn(MethodSpec.Builder m, String returnTypeFqn) {
        switch (returnTypeFqn) {
            case "void" -> m.addStatement("return");
            case "int", "java.lang.Integer" -> m.addStatement("return 0");
            case "long", "java.lang.Long" -> m.addStatement("return 0L");
            case "boolean", "java.lang.Boolean" -> m.addStatement("return false");
            default -> throw new IllegalStateException("unreachable: " + returnTypeFqn);
        }
    }

    private static TypeName returnTypeName(StatementModel st, Map<String, ResultModel> resultModels) {
        if (st.returnShape() == ReturnShape.UPDATE_COUNT) {
            return EmitSupport.typeName(st.returnTypeFqn());
        }
        TypeName element = st.scalarKind() != null
                ? EmitSupport.scalarTypeName(st.scalarKind(), st.scalarEnumType())
                : ClassName.bestGuess(resultModels.get(st.resultFqn()).fqn());
        return st.returnShape() == ReturnShape.MANY
                ? ParameterizedTypeName.get(EmitSupport.LIST, element.box())
                : element;
    }
}
