package io.github.larkbatis.runtime.handwritten;

import io.github.larkbatis.runtime.JdbcLarkBatisSession;
import io.github.larkbatis.runtime.LarkBatisTx;
import io.github.larkbatis.runtime.SqlFragment;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.List;
import javax.sql.DataSource;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * The hand-written {@code UserMapper$$Impl} runs against real JDBC (H2) and
 * behaves like a mapper should.
 */
class HandwrittenMapperTest {

    private JdbcLarkBatisSession session;
    private UserMapper mapper;

    @BeforeEach
    void setUp() throws SQLException {
        JdbcDataSource ds = new JdbcDataSource();
        // A named in-memory database would survive between tests; a fresh
        // unnamed one per test keeps them independent.
        ds.setURL("jdbc:h2:mem:handwritten_" + System.nanoTime() + ";DB_CLOSE_DELAY=-1");
        createSchema(ds);
        session = new JdbcLarkBatisSession(ds);
        mapper = new UserMapper$$Impl(session);
    }

    @AfterEach
    void noLeakedTransaction() {
        assertFalse(session.hasActiveTransaction(), "transaction scope leaked");
    }

    private static void createSchema(DataSource ds) throws SQLException {
        try (Connection c = ds.getConnection(); Statement st = c.createStatement()) {
            st.execute("CREATE TABLE users ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "name VARCHAR(100) NOT NULL, "
                    + "email VARCHAR(100), "
                    + "created_at TIMESTAMP)");
        }
    }

    @Test
    void insertAssignsGeneratedKeyAndFindByIdReadsItBack() {
        Instant createdAt = Instant.parse("2026-08-30T10:15:30Z");
        User u = new User();
        u.setName("Ada");
        u.setEmail("ada@example.com");
        u.setCreatedAt(createdAt);

        int n = mapper.insert(u);

        assertEquals(1, n);
        assertTrue(u.getId() > 0, "generated key must be assigned onto the bean");

        User found = mapper.findById(u.getId());
        assertEquals(u.getId(), found.getId());
        assertEquals("Ada", found.getName());
        assertEquals("ada@example.com", found.getEmail());
        assertEquals(createdAt, found.getCreatedAt().truncatedTo(ChronoUnit.SECONDS));
    }

    @Test
    void findByIdReturnsNullWhenNoRowMatches() {
        assertNull(mapper.findById(424242L));
    }

    @Test
    void nullColumnsComeBackAsNull() {
        User u = new User();
        u.setName("NoEmail");

        mapper.insert(u);
        User found = mapper.findById(u.getId());

        assertEquals("NoEmail", found.getName());
        assertNull(found.getEmail());
        assertNull(found.getCreatedAt());
    }

    @Test
    void mapperJoinsAnOpenTransactionAndRollsBackWithIt() {
        User u = new User();
        u.setName("Ghost");

        try (LarkBatisTx tx = session.begin()) {
            mapper.insert(u);
            assertTrue(u.getId() > 0);
            // no commit → rollback on close
        }

        assertNull(mapper.findById(u.getId()), "rolled-back insert must not be visible");
    }

    @Test
    void escapeHatchReusesTheGeneratedRowReader() {
        User a = new User();
        a.setName("A");
        mapper.insert(a);
        User b = new User();
        b.setName("B");
        mapper.insert(b);

        List<User> all = session.query(
                SqlFragment.unsafeRawSql("SELECT id, name, email, created_at FROM users ORDER BY id"),
                ps -> { },
                UserRow.READER);

        assertEquals(2, all.size());
        assertEquals("A", all.get(0).getName());
        assertEquals("B", all.get(1).getName());
    }
}
