package com.example.app;

import io.github.larkbatis.runtime.JdbcCodec;
import io.github.larkbatis.runtime.LarkBatisEmptyForeachException;
import io.github.larkbatis.runtime.LarkBatisSession;
import io.github.larkbatis.runtime.LarkBatisSql;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.processing.Generated;

/**
 * Generated by LarkBatis from {@link UserQueryMapper} — do not edit.
 * Plain JDBC, resolved at build time; the only runtime inputs are parameter values.
 */
@Generated("io.github.larkbatis.processor.LarkBatisProcessor")
public final class UserQueryMapper$$Impl implements UserQueryMapper {
    private static final String SQL_all = "SELECT id, name, email, created_at FROM users ORDER BY id";

    private static final String STMT_findByIds = "com.example.app.UserQueryMapper.findByIds";

    private static final String STMT_findByIdsPadded = "com.example.app.UserQueryMapper.findByIdsPadded";

    private static final String STMT_searchInIds = "com.example.app.UserQueryMapper.searchInIds";

    private final LarkBatisSession s;

    public UserQueryMapper$$Impl(LarkBatisSession s) {
        this.s = s;
    }

    @Override
    public List<User> search(UserQuery q) {
        boolean c0 = q.getName() != null;
        boolean c1 = q.getMinAge() != null;
        StringBuilder sb = new StringBuilder(96);
        sb.append("SELECT id, name, email, created_at FROM users");
        if (c0 | c1) {
            sb.append(" WHERE");
        }
        if (c0) {
            sb.append(" name LIKE ?");
        }
        if (c1) {
            sb.append(c0 ? " AND age >= ?" : " age >= ?");
        }
        sb.append(" ORDER BY id");
        String sql = sb.toString();
        Connection c = s.conn();
        try (PreparedStatement ps = c.prepareStatement(sql)) {
            int i = 1;
            if (c0) {
                ps.setString(i++, q.getName());
            }
            if (c1) {
                JdbcCodec.setInt(ps, i++, q.getMinAge());
            }
            try (ResultSet rs = ps.executeQuery()) {
                List<User> out = new ArrayList<>();
                while (rs.next()) {
                    out.add(UserRow.read(rs));
                }
                return out;
            }
        } catch (SQLException e) {
            throw s.translate(e, sql);
        } finally {
            s.release(c);
        }
    }

    @Override
    public List<User> byStatus(UserQuery q) {
        boolean c0 = q.getStatus() != null;
        boolean c1 = !c0;
        StringBuilder sb = new StringBuilder(112);
        sb.append("SELECT id, name, email, created_at FROM users WHERE 1 = 1");
        if (c0) {
            sb.append(" AND status = ?");
        }
        if (c1) {
            sb.append(" AND status = 'NEW'");
        }
        sb.append(" ORDER BY id");
        String sql = sb.toString();
        Connection c = s.conn();
        try (PreparedStatement ps = c.prepareStatement(sql)) {
            int i = 1;
            if (c0) {
                JdbcCodec.setEnum(ps, i++, q.getStatus());
            }
            try (ResultSet rs = ps.executeQuery()) {
                List<User> out = new ArrayList<>();
                while (rs.next()) {
                    out.add(UserRow.read(rs));
                }
                return out;
            }
        } catch (SQLException e) {
            throw s.translate(e, sql);
        } finally {
            s.release(c);
        }
    }

    @Override
    public int rename(UserQuery q) {
        boolean c0 = q.getName() != null;
        boolean c1 = q.getEmail() != null;
        StringBuilder sb = new StringBuilder(64);
        sb.append("UPDATE users");
        if (c0 | c1) {
            sb.append(" SET");
        }
        if (c0) {
            sb.append(c1 ? " name = ?," : " name = ?");
        }
        if (c1) {
            sb.append(" email = ?");
        }
        sb.append(" WHERE id = ?");
        String sql = sb.toString();
        Connection c = s.conn();
        try (PreparedStatement ps = c.prepareStatement(sql)) {
            int i = 1;
            if (c0) {
                ps.setString(i++, q.getName());
            }
            if (c1) {
                ps.setString(i++, q.getEmail());
            }
            ps.setLong(i++, q.getId());
            return ps.executeUpdate();
        } catch (SQLException e) {
            throw s.translate(e, sql);
        } finally {
            s.release(c);
        }
    }

    @Override
    public List<User> all() {
        Connection c = s.conn();
        try (PreparedStatement ps = c.prepareStatement(SQL_all)) {
            try (ResultSet rs = ps.executeQuery()) {
                List<User> out = new ArrayList<>();
                while (rs.next()) {
                    out.add(UserRow.read(rs));
                }
                return out;
            }
        } catch (SQLException e) {
            throw s.translate(e, SQL_all);
        } finally {
            s.release(c);
        }
    }

    @Override
    public List<User> findByIds(List<Long> ids) {
        StringBuilder sb = new StringBuilder(144);
        sb.append("SELECT id, name, email, created_at FROM users WHERE id IN");
        int n0 = ids.size();
        if (n0 == 0) {
            throw new LarkBatisEmptyForeachException("com.example.app.UserQueryMapper.findByIds", "list");
        }
        sb.append(" (");
        for (int k0 = 0; k0 < n0; k0++) sb.append(k0 == 0 ? " ?" : " , ?");
        sb.append(" )");
        sb.append(" ORDER BY id");
        String sql = sb.toString();
        LarkBatisSql.trackVariants(STMT_findByIds, sql);
        Connection c = s.conn();
        try (PreparedStatement ps = c.prepareStatement(sql)) {
            int i = 1;
            for (Long id : ids) {
                JdbcCodec.setLong(ps, i++, id);
            }
            try (ResultSet rs = ps.executeQuery()) {
                List<User> out = new ArrayList<>();
                while (rs.next()) {
                    out.add(UserRow.read(rs));
                }
                return out;
            }
        } catch (SQLException e) {
            throw s.translate(e, sql);
        } finally {
            s.release(c);
        }
    }

    @Override
    public List<User> findByIdsPadded(List<Long> ids) {
        int n0 = ids.size();
        if (n0 == 0) {
            throw new LarkBatisEmptyForeachException("com.example.app.UserQueryMapper.findByIdsPadded", "list");
        }
        int p0 = LarkBatisSql.padPow2(n0);
        StringBuilder sb = new StringBuilder(128);
        sb.append("SELECT id, name, email, created_at FROM users WHERE id IN");
        sb.append(" (");
        for (int k0 = 0; k0 < p0; k0++) sb.append(k0 == 0 ? " ?" : " , ?");
        sb.append(" )");
        String sql = sb.toString();
        LarkBatisSql.trackVariants(STMT_findByIdsPadded, sql);
        Connection c = s.conn();
        try (PreparedStatement ps = c.prepareStatement(sql)) {
            int i = 1;
            Long last0 = null;
            for (Long id : ids) {
                JdbcCodec.setLong(ps, i++, id);
                last0 = id;
            }
            for (int k0 = n0; k0 < p0; k0++) {
                JdbcCodec.setLong(ps, i++, last0);
            }
            try (ResultSet rs = ps.executeQuery()) {
                List<User> out = new ArrayList<>();
                while (rs.next()) {
                    out.add(UserRow.read(rs));
                }
                return out;
            }
        } catch (SQLException e) {
            throw s.translate(e, sql);
        } finally {
            s.release(c);
        }
    }

    @Override
    public List<User> searchInIds(UserQuery q) {
        boolean c0 = q.getName() != null;
        boolean c1 = q.getIds() != null;
        List<Long> src0 = null;
        StringBuilder sb = new StringBuilder(160);
        sb.append("SELECT id, name, email, created_at FROM users");
        if (c0 | c1) {
            sb.append(" WHERE");
        }
        if (c0) {
            sb.append(" name LIKE ?");
        }
        if (c1) {
            sb.append(c0 ? " AND id IN" : " id IN");
            src0 = q.getIds();
            int n0 = src0.size();
            if (n0 == 0) {
                throw new LarkBatisEmptyForeachException("com.example.app.UserQueryMapper.searchInIds", "ids");
            }
            sb.append(" (");
            for (int k0 = 0; k0 < n0; k0++) sb.append(k0 == 0 ? " ?" : " , ?");
            sb.append(" )");
        }
        sb.append(" ORDER BY id");
        String sql = sb.toString();
        LarkBatisSql.trackVariants(STMT_searchInIds, sql);
        Connection c = s.conn();
        try (PreparedStatement ps = c.prepareStatement(sql)) {
            int i = 1;
            if (c0) {
                ps.setString(i++, q.getName());
            }
            if (c1) {
                for (Long id : src0) {
                    JdbcCodec.setLong(ps, i++, id);
                }
            }
            try (ResultSet rs = ps.executeQuery()) {
                List<User> out = new ArrayList<>();
                while (rs.next()) {
                    out.add(UserRow.read(rs));
                }
                return out;
            }
        } catch (SQLException e) {
            throw s.translate(e, sql);
        } finally {
            s.release(c);
        }
    }
}
