package com.example.lbsample;

import io.github.lightbatis.runtime.JdbcLightBatisSession;
import io.github.lightbatis.runtime.LightBatisRejectedException;
import io.github.lightbatis.runtime.LightBatisTx;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.Instant;
import java.util.List;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * The generated code (not the hand-written spec) executing against real JDBC:
 * generated keys, batch keys, @OrderBy switch, scalar reads, transactions,
 * and the escape hatch reusing the generated reader.
 */
class GeneratedMapperEndToEndTest {

    private JdbcLightBatisSession session;
    private UserMapper mapper;

    @BeforeEach
    void setUp() throws SQLException {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:e2e_" + System.nanoTime() + ";DB_CLOSE_DELAY=-1");
        try (Connection c = dataSource.getConnection(); Statement st = c.createStatement()) {
            st.execute("CREATE TABLE users ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "name VARCHAR(100) NOT NULL, "
                    + "email VARCHAR(100), "
                    + "created_at TIMESTAMP)");
        }
        session = new JdbcLightBatisSession(dataSource);
        mapper = LightBatisMappers.userMapper(session);
    }

    @AfterEach
    void noLeakedTransaction() {
        assertFalse(session.hasActiveTransaction());
    }

    private static User user(String name) {
        User u = new User();
        u.setName(name);
        u.setEmail(name.toLowerCase() + "@example.com");
        u.setCreatedAt(Instant.parse("2026-08-30T10:00:00Z"));
        return u;
    }

    @Test
    void insertAssignsGeneratedKeyAndFindByIdRoundTrips() {
        User ada = user("Ada");
        assertEquals(1, mapper.insert(ada));
        assertTrue(ada.getId() > 0);

        User found = mapper.findById(ada.getId());
        assertEquals("Ada", found.getName());
        assertEquals("ada@example.com", found.getEmail());
        assertEquals(Instant.parse("2026-08-30T10:00:00Z"), found.getCreatedAt());
        assertNull(mapper.findById(999_999L));
    }

    @Test
    void batchInsertAssignsAllGeneratedKeys() {
        List<User> users = List.of(user("A"), user("B"), user("C"));
        assertEquals(3, mapper.insertAll(users));
        for (User u : users) {
            assertTrue(u.getId() > 0, "every batch row must get its key back");
        }
        assertEquals(3, mapper.countByName("%"));
        assertEquals(0, mapper.insertAll(List.of()), "empty batch short-circuits");
    }

    @Test
    void orderBySwitchAcceptsWhitelistedValueAndRejectsTheRest() {
        mapper.insert(user("Zoe"));
        mapper.insert(user("Ada"));

        List<User> byName = mapper.all("name");
        assertEquals("Ada", byName.get(0).getName());
        assertEquals("Zoe", byName.get(1).getName());

        assertThrows(LightBatisRejectedException.class, () -> mapper.all("name; DROP TABLE users"));
    }

    @Test
    void scalarSelectReadsColumnOne() {
        mapper.insert(user("Grace"));
        mapper.insert(user("Gustav"));
        mapper.insert(user("Ada"));
        assertEquals(2, mapper.countByName("G%"));
    }

    @Test
    void generatedMapperJoinsTransactions() {
        User ghost = user("Ghost");
        try (LightBatisTx tx = session.begin()) {
            mapper.insert(ghost);
        }
        assertNull(mapper.findById(ghost.getId()), "uncommitted insert must roll back");
    }

    @Test
    void escapeHatchReusesGeneratedReader() {
        mapper.insert(user("A"));
        mapper.insert(user("B"));
        mapper.insert(user("C"));
        assertEquals(2, mapper.recent(session, 2).size());
    }
}
