package com.example.app;

import io.github.lightbatis.runtime.JdbcCodec;
import io.github.lightbatis.runtime.RowReader;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Locale;
import javax.annotation.processing.Generated;

/**
 * Row reader for {@link Order} — generated by LightBatis, do not edit.
 * One reader per result class (design §04); the manual escape hatch
 * reuses {@link #READER} (design §09).
 */
@Generated("io.github.lightbatis.processor.LightBatisProcessor")
public final class OrderRow {
    public static final RowReader<Order> READER = OrderRow::read;

    private OrderRow() {
    }

    /**
     * Positional read — canonical column order: id, status, total, placedAt.
     */
    public static Order read(ResultSet rs) throws SQLException {
        Order o = new Order();
        o.setId(rs.getLong(1));
        o.setStatus(JdbcCodec.enumValue(rs, 2, Status.class));
        o.setTotal(rs.getBigDecimal(3));
        o.setPlacedAt(JdbcCodec.instant(rs, 4));
        return o;
    }

    /**
     * General read: {@code c[k]} is the ResultSet position of property {@code k}, 0 = not selected.
     */
    public static Order read(ResultSet rs, int[] c) throws SQLException {
        Order o = new Order();
        if (c[0] != 0) {
            o.setId(rs.getLong(c[0]));
        }
        if (c[1] != 0) {
            o.setStatus(JdbcCodec.enumValue(rs, c[1], Status.class));
        }
        if (c[2] != 0) {
            o.setTotal(rs.getBigDecimal(c[2]));
        }
        if (c[3] != 0) {
            o.setPlacedAt(JdbcCodec.instant(rs, c[3]));
        }
        return o;
    }

    /**
     * Name-based fallback: resolves column positions from ResultSetMetaData once, on the first row (design §04).
     * Unmatched columns are ignored, like MyBatis auto-mapping.
     */
    public static int[] columns(ResultSet rs) throws SQLException {
        ResultSetMetaData md = rs.getMetaData();
        int[] c = new int[4];
        for (int i = 1, n = md.getColumnCount(); i <= n; i++) {
            switch (md.getColumnLabel(i).replace("_", "").toLowerCase(Locale.ROOT)) {
                case "id":
                    c[0] = i;
                    break;
                case "status":
                    c[1] = i;
                    break;
                case "total":
                    c[2] = i;
                    break;
                case "placedat":
                    c[3] = i;
                    break;
                default:
                    break;
            }
        }
        return c;
    }
}
