package com.example.app;

import io.github.lightbatis.runtime.JdbcCodec;
import io.github.lightbatis.runtime.LightBatisException;
import io.github.lightbatis.runtime.LightBatisKeyCountMismatchException;
import io.github.lightbatis.runtime.LightBatisRejectedException;
import io.github.lightbatis.runtime.LightBatisSession;
import io.github.lightbatis.runtime.LightBatisSql;
import io.github.lightbatis.runtime.SqlFragment;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.processing.Generated;

/**
 * Generated by LightBatis from {@link OrderMapper} — do not edit.
 * Plain JDBC, resolved at build time (design §04); the only runtime inputs are parameter values.
 */
@Generated("io.github.lightbatis.processor.LightBatisProcessor")
public final class OrderMapper$$Impl implements OrderMapper {
    private static final String SQL_byStatus = "SELECT id, status, total, placed_at FROM orders WHERE status = ?";

    private static final String SQL_byId = "SELECT * FROM orders WHERE id = ?";

    private static final String SQL_totalAndId = "SELECT total, id FROM orders WHERE id = ?";

    private static final int[] COLS_totalAndId = { 2, 0, 1, 0 };

    private static final String SQL_countByStatus = "SELECT COUNT(*) cnt FROM orders WHERE status = ?";

    private static final String STMT_sorted = "com.example.app.OrderMapper.sorted";

    private static final String STMT_sortedBy = "com.example.app.OrderMapper.sortedBy";

    private static final String SQL_updateStatus = "UPDATE orders SET status = ? WHERE id = ?";

    private static final String SQL_insert = "INSERT INTO orders (status, total, placed_at) VALUES (?, ?, ?)";

    private static final String[] KEYS_insert = { "id" };

    private static final String SQL_insertAll = "INSERT INTO orders (status, total, placed_at) VALUES (?, ?, ?)";

    private static final String[] KEYS_insertAll = { "id" };

    private static final String SQL_delete = "DELETE FROM orders WHERE id = ?";

    private final LightBatisSession s;

    public OrderMapper$$Impl(LightBatisSession s) {
        this.s = s;
    }

    @Override
    public List<Order> byStatus(Status status) {
        Connection c = s.conn();
        try (PreparedStatement ps = c.prepareStatement(SQL_byStatus)) {
            JdbcCodec.setEnum(ps, 1, status);
            try (ResultSet rs = ps.executeQuery()) {
                List<Order> out = new ArrayList<>();
                while (rs.next()) {
                    out.add(OrderRow.read(rs));
                }
                return out;
            }
        } catch (SQLException e) {
            throw s.translate(e, SQL_byStatus);
        } finally {
            s.release(c);
        }
    }

    @Override
    public Order byId(long id) {
        Connection c = s.conn();
        try (PreparedStatement ps = c.prepareStatement(SQL_byId)) {
            ps.setLong(1, id);
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next() ? OrderRow.read(rs, OrderRow.columns(rs)) : null;
            }
        } catch (SQLException e) {
            throw s.translate(e, SQL_byId);
        } finally {
            s.release(c);
        }
    }

    @Override
    public Order totalAndId(long id) {
        Connection c = s.conn();
        try (PreparedStatement ps = c.prepareStatement(SQL_totalAndId)) {
            ps.setLong(1, id);
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next() ? OrderRow.read(rs, COLS_totalAndId) : null;
            }
        } catch (SQLException e) {
            throw s.translate(e, SQL_totalAndId);
        } finally {
            s.release(c);
        }
    }

    @Override
    public long countByStatus(Status status) {
        Connection c = s.conn();
        try (PreparedStatement ps = c.prepareStatement(SQL_countByStatus)) {
            JdbcCodec.setEnum(ps, 1, status);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    return rs.getLong(1);
                }
                throw new LightBatisException("Statement com.example.app.OrderMapper.countByStatus returned no row but the method returns a primitive", SQL_countByStatus);
            }
        } catch (SQLException e) {
            throw s.translate(e, SQL_countByStatus);
        } finally {
            s.release(c);
        }
    }

    @Override
    public List<Order> sorted(String sort) {
        String sortSql;
        switch (sort) {
            case "id":
                sortSql = "id";
                break;
            case "total":
                sortSql = "total";
                break;
            default:
                throw new LightBatisRejectedException(sort, new String[] { "id", "total" });
        }
        String sql = "SELECT id, status, total, placed_at FROM orders ORDER BY " + sortSql;
        LightBatisSql.trackVariants(STMT_sorted, sql);
        Connection c = s.conn();
        try (PreparedStatement ps = c.prepareStatement(sql)) {
            try (ResultSet rs = ps.executeQuery()) {
                List<Order> out = new ArrayList<>();
                while (rs.next()) {
                    out.add(OrderRow.read(rs));
                }
                return out;
            }
        } catch (SQLException e) {
            throw s.translate(e, sql);
        } finally {
            s.release(c);
        }
    }

    @Override
    public List<Order> sortedBy(SqlFragment sort) {
        String sql = "SELECT id, status, total, placed_at FROM orders ORDER BY " + sort.text();
        LightBatisSql.trackVariants(STMT_sortedBy, sql);
        Connection c = s.conn();
        try (PreparedStatement ps = c.prepareStatement(sql)) {
            try (ResultSet rs = ps.executeQuery()) {
                List<Order> out = new ArrayList<>();
                while (rs.next()) {
                    out.add(OrderRow.read(rs));
                }
                return out;
            }
        } catch (SQLException e) {
            throw s.translate(e, sql);
        } finally {
            s.release(c);
        }
    }

    @Override
    public int updateStatus(long id, Status status) {
        Connection c = s.conn();
        try (PreparedStatement ps = c.prepareStatement(SQL_updateStatus)) {
            JdbcCodec.setEnum(ps, 1, status);
            ps.setLong(2, id);
            return ps.executeUpdate();
        } catch (SQLException e) {
            throw s.translate(e, SQL_updateStatus);
        } finally {
            s.release(c);
        }
    }

    @Override
    public int insert(Order o) {
        Connection c = s.conn();
        try (PreparedStatement ps = c.prepareStatement(SQL_insert, KEYS_insert)) {
            JdbcCodec.setEnum(ps, 1, o.getStatus());
            ps.setBigDecimal(2, o.getTotal());
            JdbcCodec.setInstant(ps, 3, o.getPlacedAt());
            int n = ps.executeUpdate();
            try (ResultSet gk = ps.getGeneratedKeys()) {
                if (gk.next()) {
                    o.setId(gk.getLong(1));
                }
            }
            return n;
        } catch (SQLException e) {
            throw s.translate(e, SQL_insert);
        } finally {
            s.release(c);
        }
    }

    @Override
    public int insertAll(List<Order> orders) {
        if (orders.isEmpty()) {
            return 0;
        }
        Connection c = s.conn();
        try (PreparedStatement ps = c.prepareStatement(SQL_insertAll, KEYS_insertAll)) {
            for (Order order : orders) {
                JdbcCodec.setEnum(ps, 1, order.getStatus());
                ps.setBigDecimal(2, order.getTotal());
                JdbcCodec.setInstant(ps, 3, order.getPlacedAt());
                ps.addBatch();
            }
            int n = LightBatisSql.sum(ps.executeBatch());
            try (ResultSet gk = ps.getGeneratedKeys()) {
                int i = 0;
                while (gk.next() && i < orders.size()) {
                    orders.get(i).setId(gk.getLong(1));
                    i++;
                }
                if (i != orders.size()) {
                    throw new LightBatisKeyCountMismatchException("com.example.app.OrderMapper.insertAll", orders.size(), i);
                }
            }
            return n;
        } catch (SQLException e) {
            throw s.translate(e, SQL_insertAll);
        } finally {
            s.release(c);
        }
    }

    @Override
    public void delete(long id) {
        Connection c = s.conn();
        try (PreparedStatement ps = c.prepareStatement(SQL_delete)) {
            ps.setLong(1, id);
            ps.executeUpdate();
        } catch (SQLException e) {
            throw s.translate(e, SQL_delete);
        } finally {
            s.release(c);
        }
    }
}
