package com.example.app;

import io.github.larkbatis.runtime.JdbcCodec;
import io.github.larkbatis.runtime.LarkBatisNoKeyException;
import io.github.larkbatis.runtime.LarkBatisSession;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.annotation.processing.Generated;

/**
 * Generated by LarkBatis from {@link UserMapper} — do not edit.
 * Plain JDBC, resolved at build time; the only runtime inputs are parameter values.
 */
@Generated("io.github.larkbatis.processor.LarkBatisProcessor")
public final class UserMapper$$Impl implements UserMapper {
    private static final String SQL_findById = "SELECT id, name, email, created_at FROM users WHERE id = ?";

    private static final String SQL_insert = "INSERT INTO users (name, email, created_at) VALUES (?, ?, ?)";

    private static final String[] KEYS_insert = { "id" };

    private final LarkBatisSession s;

    public UserMapper$$Impl(LarkBatisSession s) {
        this.s = s;
    }

    @Override
    public User findById(long id) {
        Connection c = s.conn();
        try (PreparedStatement ps = c.prepareStatement(SQL_findById)) {
            ps.setLong(1, id);
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next() ? UserRow.read(rs) : null;
            }
        } catch (SQLException e) {
            throw s.translate(e, SQL_findById);
        } finally {
            s.release(c);
        }
    }

    @Override
    public int insert(User u) {
        Connection c = s.conn();
        try (PreparedStatement ps = c.prepareStatement(SQL_insert, KEYS_insert)) {
            ps.setString(1, u.getName());
            ps.setString(2, u.getEmail());
            JdbcCodec.setInstant(ps, 3, u.getCreatedAt());
            int n = ps.executeUpdate();
            try (ResultSet gk = ps.getGeneratedKeys()) {
                if (gk.next()) {
                    u.setId(gk.getLong(1));
                } else {
                    throw new LarkBatisNoKeyException("com.example.app.UserMapper.insert");
                }
            }
            return n;
        } catch (SQLException e) {
            throw s.translate(e, SQL_insert);
        } finally {
            s.release(c);
        }
    }
}
