package com.example.app;

import io.github.larkbatis.runtime.JdbcCodec;
import io.github.larkbatis.runtime.RowReader;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Locale;
import javax.annotation.processing.Generated;

/**
 * Row reader for {@link User} — generated by LarkBatis, do not edit.
 * One reader per result class; the manual escape hatch
 * reuses {@link #READER}.
 */
@Generated("io.github.larkbatis.processor.LarkBatisProcessor")
public final class UserRow {
    public static final RowReader<User> READER = UserRow::read;

    private UserRow() {
    }

    /**
     * Positional read — canonical column order: id, name, email, createdAt.
     */
    public static User read(ResultSet rs) throws SQLException {
        User u = new User();
        u.setId(rs.getLong(1));
        u.setName(rs.getString(2));
        u.setEmail(rs.getString(3));
        u.setCreatedAt(JdbcCodec.instant(rs, 4));
        return u;
    }

    /**
     * General read: {@code c[k]} is the ResultSet position of property {@code k}, 0 = not selected.
     */
    public static User read(ResultSet rs, int[] c) throws SQLException {
        User u = new User();
        if (c[0] != 0) {
            u.setId(rs.getLong(c[0]));
        }
        if (c[1] != 0) {
            u.setName(rs.getString(c[1]));
        }
        if (c[2] != 0) {
            u.setEmail(rs.getString(c[2]));
        }
        if (c[3] != 0) {
            u.setCreatedAt(JdbcCodec.instant(rs, c[3]));
        }
        return u;
    }

    /**
     * Name-based fallback: resolves column positions from ResultSetMetaData once, on the first row.
     * Unmatched columns are ignored, like MyBatis auto-mapping.
     */
    public static int[] columns(ResultSet rs) throws SQLException {
        ResultSetMetaData md = rs.getMetaData();
        int[] c = new int[4];
        for (int i = 1, n = md.getColumnCount(); i <= n; i++) {
            switch (md.getColumnLabel(i).replace("_", "").toLowerCase(Locale.ROOT)) {
                case "id":
                    c[0] = i;
                    break;
                case "name":
                    c[1] = i;
                    break;
                case "email":
                    c[2] = i;
                    break;
                case "createdat":
                    c[3] = i;
                    break;
                default:
                    break;
            }
        }
        return c;
    }
}
