package com.example.app;

import io.github.larkbatis.runtime.LarkBatisSession;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import javax.annotation.processing.Generated;

/**
 * Generated by LarkBatis from {@link InvoiceMapper} — do not edit.
 * Plain JDBC, resolved at build time; the only runtime inputs are parameter values.
 */
@Generated("io.github.larkbatis.processor.LarkBatisProcessor")
public final class InvoiceMapper$$Impl implements InvoiceMapper {
    private static final String SQL_findAllWithLines = "SELECT i.id AS inv_id, i.number AS inv_number, i.issued AS inv_issued, l.id AS line_id, l.sku AS line_sku, l.amount AS line_amount FROM invoice i LEFT JOIN invoice_line l ON l.invoice_id = i.id ORDER BY i.id";

    private static final int[] COLS_findAllWithLines = { 1, 2, 3 };

    private static final int[] NCOLS_findAllWithLines = { 4, 5, 6 };

    private static final String SQL_findWithLines = "SELECT i.id AS inv_id, i.number AS inv_number, i.issued AS inv_issued, l.id AS line_id, l.sku AS line_sku, l.amount AS line_amount FROM invoice i LEFT JOIN invoice_line l ON l.invoice_id = i.id WHERE i.id = ? ORDER BY i.id";

    private static final int[] COLS_findWithLines = { 1, 2, 3 };

    private static final int[] NCOLS_findWithLines = { 4, 5, 6 };

    private static final String SQL_findAllWithCustomer = "SELECT i.id AS inv_id, i.number AS inv_number, c.id AS cust_id, c.name AS cust_name FROM invoice i LEFT JOIN customer c ON c.id = i.customer_id ORDER BY i.id";

    private static final int[] COLS_findAllWithCustomer = { 1, 2, 0 };

    private static final int[] NCOLS_findAllWithCustomer = { 3, 4 };

    private static final String SQL_findAllFlat = "SELECT * FROM invoice_view ORDER BY inv_id";

    private final LarkBatisSession s;

    public InvoiceMapper$$Impl(LarkBatisSession s) {
        this.s = s;
    }

    /**
     * Column positions for the columns this statement's <resultMap> named,
     * resolved from ResultSetMetaData once, on the first row.
     */
    private static int[] cols_findAllFlat(ResultSet rs) throws SQLException {
        ResultSetMetaData md = rs.getMetaData();
        int[] c = new int[3];
        for (int i = 1, n = md.getColumnCount(); i <= n; i++) {
            switch (md.getColumnLabel(i).replace("_", "").toLowerCase(Locale.ROOT)) {
                case "invid":
                    c[0] = i;
                    break;
                case "invnumber":
                    c[1] = i;
                    break;
                case "invissued":
                    c[2] = i;
                    break;
                default:
                    break;
            }
        }
        return c;
    }

    @Override
    public List<Invoice> findAllWithLines() {
        Connection c = s.conn();
        try (PreparedStatement ps = c.prepareStatement(SQL_findAllWithLines)) {
            try (ResultSet rs = ps.executeQuery()) {
                List<Invoice> out = new ArrayList<>();
                Invoice parent = null;
                List<InvoiceLine> nested = null;
                long pk0 = 0L;
                while (rs.next()) {
                    long rk0 = rs.getLong(1);
                    if (parent == null || rk0 != pk0) {
                        parent = InvoiceRow.read(rs, COLS_findAllWithLines);
                        nested = new ArrayList<>();
                        parent.setLines(nested);
                        out.add(parent);
                        pk0 = rk0;
                    }
                    if (rs.getObject(4) != null) {
                        nested.add(InvoiceLineRow.read(rs, NCOLS_findAllWithLines));
                    }
                }
                return out;
            }
        } catch (SQLException e) {
            throw s.translate(e, SQL_findAllWithLines);
        } finally {
            s.release(c);
        }
    }

    @Override
    public Invoice findWithLines(long id) {
        Connection c = s.conn();
        try (PreparedStatement ps = c.prepareStatement(SQL_findWithLines)) {
            ps.setLong(1, id);
            try (ResultSet rs = ps.executeQuery()) {
                List<Invoice> out = new ArrayList<>();
                Invoice parent = null;
                List<InvoiceLine> nested = null;
                long pk0 = 0L;
                while (rs.next()) {
                    long rk0 = rs.getLong(1);
                    if (parent == null || rk0 != pk0) {
                        parent = InvoiceRow.read(rs, COLS_findWithLines);
                        nested = new ArrayList<>();
                        parent.setLines(nested);
                        out.add(parent);
                        pk0 = rk0;
                    }
                    if (rs.getObject(4) != null) {
                        nested.add(InvoiceLineRow.read(rs, NCOLS_findWithLines));
                    }
                }
                return out.isEmpty() ? null : out.get(0);
            }
        } catch (SQLException e) {
            throw s.translate(e, SQL_findWithLines);
        } finally {
            s.release(c);
        }
    }

    @Override
    public List<Invoice> findAllWithCustomer() {
        Connection c = s.conn();
        try (PreparedStatement ps = c.prepareStatement(SQL_findAllWithCustomer)) {
            try (ResultSet rs = ps.executeQuery()) {
                List<Invoice> out = new ArrayList<>();
                Invoice parent = null;
                long pk0 = 0L;
                while (rs.next()) {
                    long rk0 = rs.getLong(1);
                    if (parent == null || rk0 != pk0) {
                        parent = InvoiceRow.read(rs, COLS_findAllWithCustomer);
                        out.add(parent);
                        pk0 = rk0;
                        if (rs.getObject(3) != null) {
                            parent.setCustomer(CustomerRow.read(rs, NCOLS_findAllWithCustomer));
                        }
                    }
                }
                return out;
            }
        } catch (SQLException e) {
            throw s.translate(e, SQL_findAllWithCustomer);
        } finally {
            s.release(c);
        }
    }

    @Override
    public List<Invoice> findAllFlat() {
        Connection c = s.conn();
        try (PreparedStatement ps = c.prepareStatement(SQL_findAllFlat)) {
            try (ResultSet rs = ps.executeQuery()) {
                List<Invoice> out = new ArrayList<>();
                int[] cols = null;
                while (rs.next()) {
                    if (cols == null) {
                        cols = cols_findAllFlat(rs);
                    }
                    out.add(InvoiceRow.read(rs, cols));
                }
                return out;
            }
        } catch (SQLException e) {
            throw s.translate(e, SQL_findAllFlat);
        } finally {
            s.release(c);
        }
    }
}
